// Code generated by goyacc -o parser.go -p SDL grammar.y. DO NOT EDIT.

//line grammar.y:2
package parser

import __yyfmt__ "fmt"

//line grammar.y:2

import (
	// "reflect"
	"fmt"
	"io"
	"log"
)

// Function to be called by SDLParse on error.
// Needs access to the lexer passed via %parse-param.
func yyerror(yyl SDLLexer, msg string) {
	lexer := yyl.(LexerInterface)
	// line, col := lexer.Position()
	// log.Println("YYERROR MSG = ", msg)
	// errMsg := fmt.Sprintf("Error at Line %d, Col %d, Near ('%s'): %s", line, col, /* TokenString(lexer.LastToken()),*/ lexer.Text(), msg) // Added TokenString helper call
	lexer.Error(msg)
}

func yyerrok(lexer SDLLexer) {
	log.Println("Error here... not sure how to recover")
	///ErrFlag = 0
}

//line grammar.y:30
type SDLSymType struct {
	yys int
	// Basic types from lexer
	sval string // Holds raw string values like identifiers, literal content

	// AST Nodes (using pointers) - these should have NodeInfo
	file           *FileDecl
	componentDecl  *ComponentDecl
	systemDecl     *SystemDecl
	aggregatorDecl *AggregatorDecl
	node           Node // Generic interface for lists and for accessing NodeInfo
	// tokenNode   TokenNode // Generic interface for lists and for accessing NodeInfo
	expr        Expr
	chainedExpr *ChainedExpr
	stmt        Stmt
	typeDecl    *TypeDecl
	paramDecl   *ParamDecl
	usesDecl    *UsesDecl
	methodDef   *MethodDecl
	// instanceDecl removed: InstanceDecl no longer in grammar
	analyzeDecl *AnalyzeDecl
	expectBlock *ExpectationsDecl
	expectStmt  *ExpectStmt
	blockStmt   *BlockStmt
	ifStmt      *IfStmt

	distributeExpr *DistributeExpr
	caseExpr       *CaseExpr

	switchStmt *SwitchStmt
	caseStmt   *CaseStmt

	tupleExpr  *TupleExpr
	goExpr     *GoExpr
	forStmt    *ForStmt
	assignStmt *AssignmentStmt
	// optionsDecl removed
	enumDecl   *EnumDecl
	importDecl *ImportDecl
	waitExpr   *WaitExpr
	// delayStmt *DelayStmt
	sampleExpr *SampleExpr

	// Slices for lists
	nodeList               []Node
	caseExprList           []*CaseExpr
	typeDeclList           []*TypeDecl
	caseStmtList           []*CaseStmt
	importDeclList         []*ImportDecl
	compBodyItem           ComponentDeclBodyItem
	compBodyItemList       []ComponentDeclBodyItem
	sysBodyItemList        []SystemDeclBodyItem
	paramList              []*ParamDecl
	assignList             []*AssignmentStmt
	exprList               []Expr
	exprMap                map[string]Expr
	stmtList               []Stmt
	ident                  *IdentifierExpr
	identList              []*IdentifierExpr
	distributeExprCaseList []*CaseExpr
	expectStmtList         []*ExpectStmt
	methodSigItemList      []*MethodDecl

	// Add field to store position for simple tokens if needed
	// posInfo     NodeInfo
}

const SYSTEM = 57346
const USES = 57347
const AGGREGATOR = 57348
const METHOD = 57349
const ANALYZE = 57350
const EXPECT = 57351
const LET = 57352
const IF = 57353
const ELSE = 57354
const SAMPLE = 57355
const DISTRIBUTE = 57356
const DEFAULT = 57357
const RETURN = 57358
const DELAY = 57359
const WAIT = 57360
const GO = 57361
const GOBATCH = 57362
const USING = 57363
const SWITCH = 57364
const CASE = 57365
const FOR = 57366
const USE = 57367
const NATIVE = 57368
const LSQUARE = 57369
const RSQUARE = 57370
const LBRACE = 57371
const RBRACE = 57372
const OPTIONS = 57373
const ENUM = 57374
const COMPONENT = 57375
const PARAM = 57376
const IMPORT = 57377
const FROM = 57378
const AS = 57379
const ASSIGN = 57380
const COLON = 57381
const LPAREN = 57382
const RPAREN = 57383
const COMMA = 57384
const DOT = 57385
const ARROW = 57386
const LET_ASSIGN = 57387
const SEMICOLON = 57388
const INT = 57389
const FLOAT = 57390
const BOOL = 57391
const STRING = 57392
const DURATION = 57393
const INT_LITERAL = 57394
const FLOAT_LITERAL = 57395
const STRING_LITERAL = 57396
const BOOL_LITERAL = 57397
const DURATION_LITERAL = 57398
const IDENTIFIER = 57399
const OR = 57400
const AND = 57401
const EQ = 57402
const NEQ = 57403
const LT = 57404
const LTE = 57405
const GT = 57406
const GTE = 57407
const PLUS = 57408
const MUL = 57409
const DIV = 57410
const MOD = 57411
const DUAL_OP = 57412
const BINARY_NC_OP = 57413
const BINARY_OP = 57414
const UNARY_OP = 57415
const MINUS = 57416
const UMINUS = 57417

var SDLToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SYSTEM",
	"USES",
	"AGGREGATOR",
	"METHOD",
	"ANALYZE",
	"EXPECT",
	"LET",
	"IF",
	"ELSE",
	"SAMPLE",
	"DISTRIBUTE",
	"DEFAULT",
	"RETURN",
	"DELAY",
	"WAIT",
	"GO",
	"GOBATCH",
	"USING",
	"SWITCH",
	"CASE",
	"FOR",
	"USE",
	"NATIVE",
	"LSQUARE",
	"RSQUARE",
	"LBRACE",
	"RBRACE",
	"OPTIONS",
	"ENUM",
	"COMPONENT",
	"PARAM",
	"IMPORT",
	"FROM",
	"AS",
	"ASSIGN",
	"COLON",
	"LPAREN",
	"RPAREN",
	"COMMA",
	"DOT",
	"ARROW",
	"LET_ASSIGN",
	"SEMICOLON",
	"INT",
	"FLOAT",
	"BOOL",
	"STRING",
	"DURATION",
	"INT_LITERAL",
	"FLOAT_LITERAL",
	"STRING_LITERAL",
	"BOOL_LITERAL",
	"DURATION_LITERAL",
	"IDENTIFIER",
	"OR",
	"AND",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"PLUS",
	"MUL",
	"DIV",
	"MOD",
	"DUAL_OP",
	"BINARY_NC_OP",
	"BINARY_OP",
	"UNARY_OP",
	"MINUS",
	"UMINUS",
}

var SDLStatenames = [...]string{}

const SDLEofCode = 1
const SDLErrCode = 2
const SDLInitialStackSize = 16

//line grammar.y:889
// --- Go Code Section ---

// Interface for the lexer required by the parser.
type LexerInterface interface {
	Lex(lval *SDLSymType) int
	Error(s string)
	Pos() int                  // Start byte position of the last token read
	End() int                  // End byte position of the last token read
	Text() string              // Text of the last token read
	Position() (line, col int) // Added: Get line/col of last token start
	LastToken() int            // Added: Get the token code that was just lexed
}

// Parse takes an input stream and attempts to parse it according to the SDL grammar. 22222
// It returns the root of the Abstract Syntax Tree (*FileDecl) if successful, or an error.
func Parse(input io.Reader) (*Lexer, *FileDecl, error) {
	// Reset global result before parsing
	lexer := NewLexer(input)
	// Set yyDebug = 3 for verbose parser debugging output
	// yyDebug = 3
	resultCode := SDLParse(lexer) // Call the LALR parser generated by goyacc

	if resultCode != 0 {
		// A syntax error occurred. The lexer's Error method should have been called
		// and stored the error message.
		if lexer.lastError != nil {
			return lexer, nil, lexer.lastError
		}
		// Fallback error message if lexer didn't store one
		return lexer, nil, fmt.Errorf("syntax error near byte %d (Line %d, Col %d)", lexer.location.Pos, lexer.location.Line, lexer.location.Col)
	}

	// Parsing succeeded
	if lexer.parseResult == nil {
		// This indicates a potential issue with the grammar's top rule action
		return lexer, nil, fmt.Errorf("parsing finished successfully, but no AST result was produced")
	}

	return lexer, lexer.parseResult, nil
}

// The parser expects the lexer variable to be named yyLex.
// We can satisfy this by creating a global or passing it via SDLParseWithLexer.
// Using SDLParseWithLexer is cleaner.

// Example main function (optional, for standalone testing)
/*
func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: parser <input_file>")
		return
	}
	filePath := os.Args[1]
	file, err := os.Open(filePath)
	if err != nil {
		fmt.Printf("Error opening file %s: %v\n", filePath, err)
		return
	}
	defer file.Close()

	astRoot, err := Parse(file)
	if err != nil {
		fmt.Printf("Parsing failed: %v\n", err)
		// Error message should ideally include line/column from lexer
	} else {
		fmt.Println("Parsing successful!")
		// Print the AST (implement String() methods for AST nodes for nice output)
		fmt.Println(astRoot.String())
	}
}
*/

//line yacctab:1
var SDLExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 77,
	40, 108,
	-2, 149,
}

const SDLPrivate = 57344

const SDLLast = 478

var SDLAct = [...]uint8{
	198, 131, 237, 128, 197, 124, 178, 170, 176, 168,
	56, 113, 114, 133, 173, 55, 53, 156, 125, 157,
	73, 169, 24, 214, 105, 57, 73, 43, 61, 154,
	153, 135, 54, 106, 25, 67, 66, 72, 39, 20,
	27, 96, 95, 72, 26, 23, 80, 126, 127, 22,
	21, 37, 251, 248, 230, 220, 224, 77, 192, 79,
	99, 78, 119, 118, 62, 191, 190, 71, 97, 118,
	76, 249, 68, 151, 210, 107, 189, 188, 241, 104,
	90, 91, 92, 93, 94, 83, 103, 110, 62, 102,
	186, 116, 13, 98, 99, 205, 121, 132, 134, 144,
	145, 129, 130, 28, 145, 99, 138, 163, 70, 29,
	42, 221, 142, 136, 9, 204, 149, 164, 152, 100,
	14, 12, 69, 11, 143, 141, 33, 159, 160, 147,
	96, 95, 115, 158, 3, 139, 35, 32, 165, 228,
	206, 137, 77, 77, 79, 79, 78, 78, 161, 162,
	111, 30, 65, 193, 51, 79, 76, 97, 187, 63,
	16, 202, 250, 229, 203, 101, 48, 201, 49, 90,
	91, 92, 93, 94, 83, 199, 200, 17, 15, 183,
	64, 19, 208, 209, 211, 212, 47, 50, 227, 213,
	58, 207, 108, 215, 12, 47, 155, 108, 109, 36,
	194, 219, 34, 31, 16, 117, 112, 223, 246, 218,
	77, 38, 79, 234, 78, 222, 225, 46, 226, 123,
	6, 231, 244, 245, 235, 232, 236, 177, 238, 239,
	216, 240, 217, 84, 195, 196, 120, 238, 148, 247,
	166, 243, 167, 242, 174, 45, 44, 52, 122, 87,
	77, 81, 79, 77, 78, 79, 252, 78, 89, 253,
	96, 95, 88, 82, 86, 80, 126, 127, 96, 95,
	140, 85, 175, 80, 126, 127, 108, 172, 233, 18,
	5, 10, 59, 60, 40, 41, 8, 97, 7, 4,
	75, 2, 96, 95, 1, 97, 146, 0, 0, 90,
	91, 92, 93, 94, 83, 0, 0, 90, 91, 92,
	93, 94, 150, 0, 0, 0, 0, 96, 95, 97,
	129, 130, 80, 126, 127, 0, 0, 0, 129, 130,
	0, 90, 91, 92, 93, 94, 83, 0, 0, 0,
	0, 0, 0, 0, 97, 0, 0, 0, 0, 0,
	0, 0, 129, 130, 0, 0, 90, 91, 92, 93,
	94, 83, 180, 183, 0, 96, 95, 0, 182, 0,
	80, 0, 0, 0, 184, 0, 181, 129, 130, 0,
	0, 108, 171, 180, 183, 0, 96, 95, 0, 182,
	0, 80, 97, 0, 0, 184, 0, 181, 179, 0,
	0, 0, 108, 0, 90, 91, 92, 93, 94, 83,
	0, 0, 0, 97, 0, 96, 95, 0, 0, 179,
	80, 0, 0, 0, 0, 90, 91, 92, 93, 94,
	83, 0, 185, 96, 95, 0, 0, 0, 80, 0,
	0, 0, 97, 0, 0, 0, 0, 0, 0, 0,
	74, 0, 0, 0, 90, 91, 92, 93, 94, 83,
	97, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 90, 91, 92, 93, 94, 83,
}

var SDLPact = [...]int16{
	-1000, -1000, 88, -1000, -1000, -1000, -1000, -1000, -1000, 171,
	-1000, -18, -7, -8, -12, -23, -13, -23, 67, -1000,
	114, 174, 97, 173, -1000, 96, 170, -1000, -3, -18,
	-19, 161, -25, -1000, -32, -25, 152, -1000, -1000, -1000,
	150, 161, -1000, -1000, -1000, -1000, -1000, -21, -22, -23,
	127, 81, 66, -1000, -20, 420, 63, -1000, 78, 135,
	152, -1000, -1000, -23, -1000, -1000, -14, -24, 163, 169,
	-25, 112, 179, -20, -1000, -1000, -1000, -1000, -1000, 92,
	-32, 178, -1000, 26, -1000, -1000, -1000, -1000, 19, -1000,
	-1000, -1000, -1000, -1000, -1000, 304, 304, 304, -1000, -26,
	-20, -1000, -1000, -1000, 103, 304, 95, -1000, -1000, -1000,
	-1000, 304, -20, 58, -1000, 255, 52, 304, -27, -28,
	167, -1000, -55, -1000, -1000, -1000, 247, 304, 92, 279,
	279, -1000, -1000, 65, 76, -1000, -1000, 304, -1000, -36,
	352, 402, -1000, 62, -1000, -20, -1000, 35, 24, -1000,
	20, 117, 172, -1000, -1000, 304, 279, 279, -1000, -1000,
	247, -1000, -1000, 304, -1000, -1000, 74, 53, -1000, 102,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-32, 304, 28, 304, 304, -1000, -1000, -1000, 304, -1000,
	-34, -1000, 304, -1000, -1000, 194, 304, -1000, 11, -1000,
	-1000, -1000, -1000, 70, -1000, -36, 304, 18, 373, -1000,
	-1000, 163, 159, -1000, 101, -1000, 133, -1000, 10, -1000,
	304, -1000, -1000, -1000, 304, -1000, 201, 304, 304, -1000,
	304, 36, -1000, -1000, 168, 193, 304, -1000, 9, -1000,
	29, -1000, -1000, -1000, 132, -1000, 8, -1000, 373, -1000,
	-1000, 373, -1000, -1000,
}

var SDLPgo = [...]int16{
	0, 294, 291, 290, 289, 217, 288, 286, 110, 285,
	284, 28, 283, 282, 15, 281, 10, 181, 280, 279,
	7, 278, 277, 14, 272, 271, 6, 270, 264, 0,
	18, 3, 263, 1, 262, 258, 251, 249, 5, 248,
	27, 16, 247, 154, 12, 11, 246, 245, 22, 244,
	9, 242, 240, 8, 13, 238, 236, 4, 235, 234,
	233, 232, 230, 227, 2, 226, 224, 223, 222, 219,
}

var SDLR1 = [...]int8{
	0, 1, 2, 2, 2, 2, 4, 4, 4, 4,
	4, 5, 5, 15, 16, 16, 18, 19, 19, 17,
	17, 48, 48, 13, 13, 12, 12, 11, 11, 10,
	10, 9, 9, 8, 8, 8, 8, 40, 40, 40,
	44, 44, 44, 45, 45, 46, 46, 47, 43, 43,
	42, 42, 41, 41, 6, 6, 7, 14, 14, 3,
	52, 52, 51, 51, 50, 27, 27, 20, 20, 20,
	20, 20, 20, 20, 20, 26, 49, 22, 24, 24,
	38, 38, 55, 55, 54, 54, 53, 21, 21, 21,
	25, 56, 56, 28, 69, 69, 69, 69, 29, 29,
	29, 39, 39, 39, 30, 30, 30, 31, 31, 36,
	36, 36, 36, 36, 36, 36, 36, 37, 32, 32,
	32, 32, 32, 35, 34, 34, 33, 33, 33, 60,
	59, 59, 58, 58, 57, 57, 62, 62, 61, 61,
	63, 66, 66, 65, 65, 64, 68, 68, 67, 23,
	23,
}

var SDLR2 = [...]int8{
	0, 1, 0, 2, 2, 2, 1, 1, 1, 3,
	1, 6, 5, 5, 1, 3, 4, 1, 3, 1,
	3, 4, 5, 0, 1, 1, 2, 1, 2, 0,
	1, 1, 2, 1, 1, 1, 1, 3, 4, 5,
	1, 3, 4, 1, 3, 3, 6, 3, 0, 1,
	1, 3, 2, 4, 8, 5, 3, 0, 2, 1,
	0, 1, 1, 3, 3, 0, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 3, 3, 4, 2, 2,
	2, 4, 3, 5, 1, 3, 4, 0, 2, 2,
	2, 0, 1, 5, 2, 2, 3, 3, 1, 1,
	1, 1, 3, 3, 1, 2, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 3, 1, 1,
	1, 1, 1, 4, 3, 3, 3, 4, 4, 6,
	0, 1, 1, 2, 3, 4, 0, 1, 3, 4,
	6, 0, 1, 1, 2, 3, 0, 1, 3, 1,
	1,
}

var SDLChk = [...]int16{
	-1000, -1, -2, 46, -4, -18, -5, -6, -7, 26,
	-15, 35, 33, 4, 32, 7, 33, 6, -19, -17,
	57, 57, 57, 57, -48, 57, 57, -48, 36, 42,
	37, 29, 40, 29, 29, 40, 29, 54, -17, 57,
	-10, -9, -8, -40, -46, -47, -5, 34, 5, 7,
	26, -43, -42, -41, 57, -14, -16, 57, -43, -13,
	-12, -11, -40, 7, 30, -8, 57, 57, -48, 41,
	42, -44, 57, 40, 30, -3, -23, -33, -38, -31,
	18, -36, -32, 57, -60, -25, -28, -37, -34, -35,
	52, 53, 54, 55, 56, 14, 13, 40, 30, 42,
	41, 30, -11, -48, -44, 38, 57, -26, 29, 29,
	-41, 38, 27, -45, -44, 40, -16, 27, 43, 43,
	-56, -29, -39, -69, -38, -30, 19, 20, -31, 73,
	74, -33, -29, -54, -29, 57, -44, 38, -29, 40,
	-27, -14, -29, -45, 41, 42, 41, -54, -55, -29,
	57, 21, -29, 57, 57, 29, 72, 74, -26, -29,
	-29, -30, -30, 42, 41, -29, -52, -51, -50, 57,
	-20, 30, -22, -23, -49, -24, -53, -63, -26, 46,
	10, 24, 16, 11, 22, 30, 28, -44, 42, 41,
	42, 41, 38, -33, 28, -59, -58, -57, -29, -30,
	-30, -26, -29, -29, 41, 42, 38, -16, -29, -29,
	46, -29, -29, -29, 57, -29, -62, -61, 15, -57,
	44, 41, -50, -29, 38, -20, -26, 29, 38, 30,
	44, -29, -29, -21, 12, -66, -65, -64, -29, -29,
	-29, 42, -53, -26, -68, -67, 15, -64, 44, 42,
	30, 44, -20, -20,
}

var SDLDef = [...]int16{
	2, -2, 1, 3, 4, 5, 6, 7, 8, 0,
	10, 0, 0, 0, 0, 0, 0, 0, 0, 17,
	19, 0, 0, 0, 9, 0, 0, 56, 0, 0,
	0, 29, 48, 57, 0, 48, 23, 16, 18, 20,
	0, 30, 31, 33, 34, 35, 36, 0, 0, 0,
	0, 0, 49, 50, 0, 0, 0, 14, 0, 0,
	24, 25, 27, 0, 12, 32, 0, 0, 0, 0,
	0, 52, 40, 0, 55, 58, 59, -2, 150, 0,
	0, 107, 109, 110, 111, 112, 113, 114, 115, 116,
	118, 119, 120, 121, 122, 91, 0, 0, 13, 0,
	21, 11, 26, 28, 37, 0, 45, 47, 65, 57,
	51, 0, 0, 0, 43, 0, 80, 0, 0, 0,
	0, 92, 98, 99, 100, 101, 0, 0, 104, 0,
	0, 108, 90, 0, 84, 15, 22, 0, 38, 60,
	0, 0, 53, 0, 41, 0, 126, 0, 0, 84,
	110, 0, 0, 124, 125, 130, 0, 0, 94, 95,
	0, 105, 106, 0, 117, 39, 0, 61, 62, 0,
	66, 75, 67, 68, 69, 70, 71, 72, 73, 74,
	0, 0, 0, 0, 0, 54, 42, 44, 0, 127,
	0, 128, 0, 81, 123, 136, 131, 132, 0, 102,
	103, 96, 97, 85, 46, 0, 0, 0, 0, 78,
	79, 0, 0, 85, 0, 82, 0, 137, 0, 133,
	0, 93, 63, 64, 0, 76, 87, 141, 0, 129,
	0, 134, 77, 86, 0, 146, 142, 143, 0, 83,
	138, 135, 88, 89, 0, 147, 0, 144, 0, 139,
	140, 0, 145, 148,
}

var SDLTok1 = [...]int8{
	1,
}

var SDLTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75,
}

var SDLTok3 = [...]int8{
	0,
}

var SDLErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	SDLDebug        = 0
	SDLErrorVerbose = false
)

type SDLLexer interface {
	Lex(lval *SDLSymType) int
	Error(s string)
}

type SDLParser interface {
	Parse(SDLLexer) int
	Lookahead() int
}

type SDLParserImpl struct {
	lval  SDLSymType
	stack [SDLInitialStackSize]SDLSymType
	char  int
}

func (p *SDLParserImpl) Lookahead() int {
	return p.char
}

func SDLNewParser() SDLParser {
	return &SDLParserImpl{}
}

const SDLFlag = -1000

func SDLTokname(c int) string {
	if c >= 1 && c-1 < len(SDLToknames) {
		if SDLToknames[c-1] != "" {
			return SDLToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func SDLStatname(s int) string {
	if s >= 0 && s < len(SDLStatenames) {
		if SDLStatenames[s] != "" {
			return SDLStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func SDLErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !SDLErrorVerbose {
		return "syntax error"
	}

	for _, e := range SDLErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + SDLTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(SDLPact[state])
	for tok := TOKSTART; tok-1 < len(SDLToknames); tok++ {
		if n := base + tok; n >= 0 && n < SDLLast && int(SDLChk[int(SDLAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if SDLDef[state] == -2 {
		i := 0
		for SDLExca[i] != -1 || int(SDLExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; SDLExca[i] >= 0; i += 2 {
			tok := int(SDLExca[i])
			if tok < TOKSTART || SDLExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if SDLExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += SDLTokname(tok)
	}
	return res
}

func SDLlex1(lex SDLLexer, lval *SDLSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(SDLTok1[0])
		goto out
	}
	if char < len(SDLTok1) {
		token = int(SDLTok1[char])
		goto out
	}
	if char >= SDLPrivate {
		if char < SDLPrivate+len(SDLTok2) {
			token = int(SDLTok2[char-SDLPrivate])
			goto out
		}
	}
	for i := 0; i < len(SDLTok3); i += 2 {
		token = int(SDLTok3[i+0])
		if token == char {
			token = int(SDLTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(SDLTok2[1]) /* unknown char */
	}
	if SDLDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", SDLTokname(token), uint(char))
	}
	return char, token
}

func SDLParse(SDLlex SDLLexer) int {
	return SDLNewParser().Parse(SDLlex)
}

func (SDLrcvr *SDLParserImpl) Parse(SDLlex SDLLexer) int {
	var SDLn int
	var SDLVAL SDLSymType
	var SDLDollar []SDLSymType
	_ = SDLDollar // silence set and not used
	SDLS := SDLrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	SDLstate := 0
	SDLrcvr.char = -1
	SDLtoken := -1 // SDLrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		SDLstate = -1
		SDLrcvr.char = -1
		SDLtoken = -1
	}()
	SDLp := -1
	goto SDLstack

ret0:
	return 0

ret1:
	return 1

SDLstack:
	/* put a state and value onto the stack */
	if SDLDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", SDLTokname(SDLtoken), SDLStatname(SDLstate))
	}

	SDLp++
	if SDLp >= len(SDLS) {
		nyys := make([]SDLSymType, len(SDLS)*2)
		copy(nyys, SDLS)
		SDLS = nyys
	}
	SDLS[SDLp] = SDLVAL
	SDLS[SDLp].yys = SDLstate

SDLnewstate:
	SDLn = int(SDLPact[SDLstate])
	if SDLn <= SDLFlag {
		goto SDLdefault /* simple state */
	}
	if SDLrcvr.char < 0 {
		SDLrcvr.char, SDLtoken = SDLlex1(SDLlex, &SDLrcvr.lval)
	}
	SDLn += SDLtoken
	if SDLn < 0 || SDLn >= SDLLast {
		goto SDLdefault
	}
	SDLn = int(SDLAct[SDLn])
	if int(SDLChk[SDLn]) == SDLtoken { /* valid shift */
		SDLrcvr.char = -1
		SDLtoken = -1
		SDLVAL = SDLrcvr.lval
		SDLstate = SDLn
		if Errflag > 0 {
			Errflag--
		}
		goto SDLstack
	}

SDLdefault:
	/* default state action */
	SDLn = int(SDLDef[SDLstate])
	if SDLn == -2 {
		if SDLrcvr.char < 0 {
			SDLrcvr.char, SDLtoken = SDLlex1(SDLlex, &SDLrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if SDLExca[xi+0] == -1 && int(SDLExca[xi+1]) == SDLstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			SDLn = int(SDLExca[xi+0])
			if SDLn < 0 || SDLn == SDLtoken {
				break
			}
		}
		SDLn = int(SDLExca[xi+1])
		if SDLn < 0 {
			goto ret0
		}
	}
	if SDLn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			SDLlex.Error(SDLErrorMessage(SDLstate, SDLtoken))
			Nerrs++
			if SDLDebug >= 1 {
				__yyfmt__.Printf("%s", SDLStatname(SDLstate))
				__yyfmt__.Printf(" saw %s\n", SDLTokname(SDLtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for SDLp >= 0 {
				SDLn = int(SDLPact[SDLS[SDLp].yys]) + SDLErrCode
				if SDLn >= 0 && SDLn < SDLLast {
					SDLstate = int(SDLAct[SDLn]) /* simulate a shift of "error" */
					if int(SDLChk[SDLstate]) == SDLErrCode {
						goto SDLstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if SDLDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", SDLS[SDLp].yys)
				}
				SDLp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if SDLDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", SDLTokname(SDLtoken))
			}
			if SDLtoken == SDLEofCode {
				goto ret1
			}
			SDLrcvr.char = -1
			SDLtoken = -1
			goto SDLnewstate /* try again in the same state */
		}
	}

	/* reduction by production SDLn */
	if SDLDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", SDLn, SDLStatname(SDLstate))
	}

	SDLnt := SDLn
	SDLpt := SDLp
	_ = SDLpt // guard against "declared and not used"

	SDLp -= int(SDLR2[SDLn])
	// SDLp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if SDLp+1 >= len(SDLS) {
		nyys := make([]SDLSymType, len(SDLS)*2)
		copy(nyys, SDLS)
		SDLS = nyys
	}
	SDLVAL = SDLS[SDLp+1]

	/* consult goto table to find next state */
	SDLn = int(SDLR1[SDLn])
	SDLg := int(SDLPgo[SDLn])
	SDLj := SDLg + SDLS[SDLp].yys + 1

	if SDLj >= SDLLast {
		SDLstate = int(SDLAct[SDLg])
	} else {
		SDLstate = int(SDLAct[SDLj])
		if int(SDLChk[SDLstate]) != -SDLn {
			SDLstate = int(SDLAct[SDLg])
		}
	}
	// dummy call; replaced with literal code
	switch SDLnt {

	case 1:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:183
		{
			ni := NodeInfo{}
			if len(SDLDollar[1].nodeList) > 0 {
				ni.StartPos = SDLDollar[1].nodeList[0].Pos()
				ni.StopPos = SDLDollar[1].nodeList[len(SDLDollar[1].nodeList)-1].End()
			}
			SDLlex.(*Lexer).parseResult = &FileDecl{NodeInfo: ni, Declarations: SDLDollar[1].nodeList}
			// $$ = &File{NodeInfo: ni, Declarations: $1}
		}
	case 2:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:195
		{
			SDLVAL.nodeList = []Node{}
		}
	case 3:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:196
		{
			SDLVAL.nodeList = SDLDollar[1].nodeList
		}
	case 4:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:197
		{
			SDLVAL.nodeList = append(SDLDollar[1].nodeList, SDLDollar[2].node)
		}
	case 5:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:200
		{
			for _, imp := range SDLDollar[2].importDeclList {
				SDLDollar[1].nodeList = append(SDLDollar[1].nodeList, imp)
			}
			SDLVAL.nodeList = SDLDollar[1].nodeList
		}
	case 6:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:209
		{
			SDLVAL.node = SDLDollar[1].componentDecl
		}
	case 7:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:210
		{
			SDLVAL.node = SDLDollar[1].systemDecl
		}
	case 8:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:211
		{
			SDLVAL.node = SDLDollar[1].aggregatorDecl
		}
	case 9:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:212
		{
			SDLDollar[3].methodDef.IsNative = true
			SDLVAL.node = SDLDollar[3].methodDef
		}
	case 10:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:216
		{
			SDLVAL.node = SDLDollar[1].enumDecl
		}
	case 11:
		SDLDollar = SDLS[SDLpt-6 : SDLpt+1]
//line grammar.y:222
		{ // COMPONENT($1) ... RBRACE($5)
			SDLVAL.componentDecl = &ComponentDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[6].node.(Node).End()),
				Name:     SDLDollar[3].ident,
				Body:     SDLDollar[5].compBodyItemList,
				IsNative: true,
			}
		}
	case 12:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:230
		{ // COMPONENT($1) ... RBRACE($5)
			SDLVAL.componentDecl = &ComponentDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[5].node.(Node).End()),
				Name:     SDLDollar[2].ident,
				Body:     SDLDollar[4].compBodyItemList,
			}
		}
	case 13:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:240
		{ // ENUM($1) IDENTIFIER($2) ... RBRACE($5)
			SDLVAL.enumDecl = &EnumDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[5].node.(Node).End()),
				Name:     SDLDollar[2].ident, // $2 is an IdentifierExpr from lexer, has Pos/End
				Values:   SDLDollar[4].identList,
			}
		}
	case 14:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:250
		{
			SDLVAL.identList = []*IdentifierExpr{SDLDollar[1].ident}
		}
	case 15:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:251
		{
			SDLVAL.identList = append(SDLDollar[1].identList, SDLDollar[3].ident)
		}
	case 16:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:255
		{ // IMPORT($1) STRING_LITERAL($2)
			path := SDLDollar[4].expr.(*LiteralExpr)
			for _, imp := range SDLDollar[2].importDeclList {
				imp.Path = path
			}
			SDLVAL.importDeclList = SDLDollar[2].importDeclList
		}
	case 17:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:264
		{
			SDLVAL.importDeclList = []*ImportDecl{SDLDollar[1].importDecl}
		}
	case 18:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:265
		{
			SDLVAL.importDeclList = append(SDLVAL.importDeclList, SDLDollar[3].importDecl)
		}
	case 19:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:268
		{
			SDLVAL.importDecl = &ImportDecl{ImportedItem: SDLDollar[1].ident, Alias: SDLDollar[1].ident}
		}
	case 20:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:269
		{
			SDLVAL.importDecl = &ImportDecl{ImportedItem: SDLDollar[1].ident, Alias: SDLDollar[3].ident}
		}
	case 21:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:273
		{ // METHOD($1) ... BlockStmt($6)
			SDLVAL.methodDef = &MethodDecl{
				NodeInfo:   NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[4].node.End()),
				Name:       SDLDollar[1].ident,
				Parameters: SDLDollar[3].paramList,
			}
		}
	case 22:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:280
		{ // METHOD($1) ... BlockStmt($8)
			SDLVAL.methodDef = &MethodDecl{
				NodeInfo:   NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[5].typeDecl.End()),
				Name:       SDLDollar[1].ident,
				Parameters: SDLDollar[3].paramList,
				ReturnType: SDLDollar[5].typeDecl,
			}
		}
	case 23:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:291
		{
			SDLVAL.compBodyItemList = []ComponentDeclBodyItem{}
		}
	case 24:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:292
		{
			SDLVAL.compBodyItemList = SDLDollar[1].compBodyItemList
		}
	case 25:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:296
		{
			SDLVAL.compBodyItemList = []ComponentDeclBodyItem{SDLDollar[1].compBodyItem}
		}
	case 26:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:297
		{
			SDLVAL.compBodyItemList = append(SDLDollar[1].compBodyItemList, SDLDollar[2].compBodyItem)
		}
	case 27:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:301
		{
			SDLVAL.compBodyItem = SDLDollar[1].paramDecl
		}
	case 28:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:302
		{
			SDLVAL.compBodyItem = SDLDollar[2].methodDef
		}
	case 29:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:307
		{
			SDLVAL.compBodyItemList = []ComponentDeclBodyItem{}
		}
	case 30:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:308
		{
			SDLVAL.compBodyItemList = SDLDollar[1].compBodyItemList
		}
	case 31:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:312
		{
			SDLVAL.compBodyItemList = []ComponentDeclBodyItem{SDLDollar[1].compBodyItem}
		}
	case 32:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:313
		{
			SDLVAL.compBodyItemList = append(SDLDollar[1].compBodyItemList, SDLDollar[2].compBodyItem)
		}
	case 33:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:317
		{
			SDLVAL.compBodyItem = SDLDollar[1].paramDecl
		}
	case 34:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:318
		{
			SDLVAL.compBodyItem = SDLDollar[1].usesDecl
		}
	case 35:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:319
		{
			SDLVAL.compBodyItem = SDLDollar[1].methodDef
		}
	case 36:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:320
		{
			SDLVAL.compBodyItem = SDLDollar[1].componentDecl
		}
	case 37:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:324
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].typeDecl.End()),
				Name:     SDLDollar[2].ident,
				TypeDecl: SDLDollar[3].typeDecl, // TypeDecl also needs to have NodeInfo
			}
		}
	case 38:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:331
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo:     NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[4].expr.End()),
				Name:         SDLDollar[2].ident,
				DefaultValue: SDLDollar[4].expr,
			}
		}
	case 39:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:338
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo:     NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[5].expr.End()),
				Name:         SDLDollar[2].ident,
				TypeDecl:     SDLDollar[3].typeDecl,
				DefaultValue: SDLDollar[5].expr,
			}
		}
	case 40:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:350
		{
			identNode := SDLDollar[1].ident
			SDLVAL.typeDecl = &TypeDecl{
				NodeInfo: identNode.NodeInfo,
				Name:     identNode.Value,
			}
		}
	case 41:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:357
		{ // Tuple type
			if len(SDLDollar[2].typeDeclList) == 1 {
				SDLVAL.typeDecl = SDLDollar[2].typeDeclList[0]
			} else {
				SDLVAL.typeDecl = &TypeDecl{
					NodeInfo: NewNodeInfo(SDLDollar[1].node.Pos(), SDLDollar[3].node.Pos()),
					Name:     "Tuple",
					Args:     SDLDollar[2].typeDeclList,
				}
			}
		}
	case 42:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:368
		{
			identNode := SDLDollar[1].ident
			SDLVAL.typeDecl = &TypeDecl{
				NodeInfo: identNode.NodeInfo,
				Name:     identNode.Value,
				Args:     SDLDollar[3].typeDeclList,
			}
		}
	case 43:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:384
		{
			SDLVAL.typeDeclList = []*TypeDecl{SDLDollar[1].typeDecl}
		}
	case 44:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:385
		{
			SDLVAL.typeDeclList = append(SDLDollar[1].typeDeclList, SDLDollar[3].typeDecl)
		}
	case 45:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:389
		{ // USES($1) ...
			SDLVAL.usesDecl = &UsesDecl{
				NodeInfo:      NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].ident.End()),
				Name:          SDLDollar[2].ident,
				ComponentName: SDLDollar[3].ident,
			}
		}
	case 46:
		SDLDollar = SDLS[SDLpt-6 : SDLpt+1]
//line grammar.y:397
		{
			SDLVAL.usesDecl = &UsesDecl{
				NodeInfo:      NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[6].node.End()),
				Name:          SDLDollar[2].ident,
				ComponentName: SDLDollar[3].ident,
				Overrides:     SDLDollar[5].assignList,
			}
		}
	case 47:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:408
		{ // METHOD($1) ... BlockStmt($6)
			SDLDollar[2].methodDef.Body = SDLDollar[3].blockStmt
			SDLDollar[2].methodDef.NodeInfo.StopPos = SDLDollar[3].blockStmt.End()
			SDLVAL.methodDef = SDLDollar[2].methodDef
		}
	case 48:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:416
		{
			SDLVAL.paramList = []*ParamDecl{}
		}
	case 49:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:417
		{
			SDLVAL.paramList = SDLDollar[1].paramList
		}
	case 50:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:421
		{
			SDLVAL.paramList = []*ParamDecl{SDLDollar[1].paramDecl}
		}
	case 51:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:422
		{
			SDLVAL.paramList = append(SDLDollar[1].paramList, SDLDollar[3].paramDecl)
		}
	case 52:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:426
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[2].typeDecl.End()),
				Name:     SDLDollar[1].ident,
				TypeDecl: SDLDollar[2].typeDecl, // TypeDecl also needs to have NodeInfo
			}
		}
	case 53:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:433
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo:     NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[4].expr.End()),
				Name:         SDLDollar[1].ident,
				TypeDecl:     SDLDollar[2].typeDecl,
				DefaultValue: SDLDollar[4].expr,
			}
		}
	case 54:
		SDLDollar = SDLS[SDLpt-8 : SDLpt+1]
//line grammar.y:448
		{
			SDLVAL.systemDecl = &SystemDecl{
				NodeInfo:   NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[8].node.(Node).End()),
				Name:       SDLDollar[2].ident,
				Parameters: SDLDollar[4].paramList,
				Body:       SDLDollar[7].sysBodyItemList,
			}
		}
	case 55:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:456
		{
			SDLVAL.systemDecl = &SystemDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[5].node.(Node).End()),
				Name:     SDLDollar[2].ident,
				Body:     SDLDollar[4].sysBodyItemList,
			}
		}
	case 56:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:466
		{ // SYSTEM($1) ... RBRACE($5)
			SDLVAL.aggregatorDecl = &AggregatorDecl{
				NodeInfo:   NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].methodDef.End()),
				Name:       SDLDollar[3].methodDef.Name,
				Parameters: SDLDollar[3].methodDef.Parameters,
				ReturnType: SDLDollar[3].methodDef.ReturnType,
			}
		}
	case 57:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:477
		{
			SDLVAL.sysBodyItemList = []SystemDeclBodyItem{}
		}
	case 58:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:478
		{
			SDLVAL.sysBodyItemList = append(SDLDollar[1].sysBodyItemList, SDLDollar[2].node.(SystemDeclBodyItem))
		}
	case 59:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:485
		{
			SDLVAL.node = SDLDollar[1].stmt
		}
	case 60:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:489
		{
			SDLVAL.assignList = []*AssignmentStmt{}
		}
	case 61:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:490
		{
			SDLVAL.assignList = SDLDollar[1].assignList
		}
	case 62:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:494
		{
			SDLVAL.assignList = []*AssignmentStmt{SDLDollar[1].assignStmt}
		}
	case 63:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:495
		{
			SDLVAL.assignList = append(SDLDollar[1].assignList, SDLDollar[3].assignStmt)
		}
	case 64:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:499
		{ // IDENTIFIER($1) ...
			SDLVAL.assignStmt = &AssignmentStmt{
				NodeInfo: NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[3].expr.End()),
				Var:      SDLDollar[1].ident,
				Value:    SDLDollar[3].expr,
			}
		}
	case 65:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:510
		{
			SDLVAL.stmtList = []Stmt{}
		}
	case 66:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:511
		{
			SDLVAL.stmtList = SDLDollar[1].stmtList
			if SDLDollar[2].stmt != nil {
				SDLVAL.stmtList = append(SDLVAL.stmtList, SDLDollar[2].stmt)
			}
		}
	case 67:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:519
		{
			SDLVAL.stmt = SDLDollar[1].stmt
		}
	case 68:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:520
		{
			SDLVAL.stmt = SDLDollar[1].stmt
		}
	case 69:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:521
		{
			SDLVAL.stmt = SDLDollar[1].forStmt
		}
	case 70:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:522
		{
			SDLVAL.stmt = SDLDollar[1].stmt
		}
	case 71:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:523
		{
			SDLVAL.stmt = SDLDollar[1].ifStmt
		}
	case 72:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:524
		{
			SDLVAL.stmt = SDLDollar[1].switchStmt
		}
	case 73:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:525
		{
			SDLVAL.stmt = SDLDollar[1].blockStmt
		}
	case 74:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:526
		{
			SDLVAL.stmt = nil
		}
	case 75:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:531
		{
			SDLVAL.blockStmt = &BlockStmt{NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].node.(Node).End()), Statements: SDLDollar[2].stmtList}
		}
	case 76:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:536
		{
			SDLVAL.forStmt = &ForStmt{NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].stmt.End()), Condition: SDLDollar[2].expr, Body: SDLDollar[3].stmt}
		}
	case 77:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:542
		{ // LET($1) ...
			SDLVAL.stmt = &LetStmt{
				NodeInfo:  NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[4].expr.End()),
				Variables: SDLDollar[2].identList,
				Value:     SDLDollar[4].expr,
			}
		}
	case 78:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:567
		{
			SDLVAL.stmt = &ReturnStmt{NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.(Node).End()), ReturnValue: SDLDollar[2].expr}
		}
	case 79:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:568
		{
			SDLVAL.stmt = &ReturnStmt{NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].node.(Node).End()), ReturnValue: nil}
		}
	case 80:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:574
		{ // WAIT($1) IDENTIFIER($2) ...
			idents := SDLDollar[2].identList
			endNode := idents[len(idents)-1] // End at the last identifier in the list
			SDLVAL.expr = &WaitExpr{FutureNames: idents}
			SDLVAL.expr.(*WaitExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.Pos(), endNode.End())
		}
	case 81:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:580
		{ // WAIT($1) IDENTIFIER($2) ...
			idents := SDLDollar[2].identList
			endNode := idents[len(idents)-1] // End at the last identifier in the list
			SDLVAL.expr = &WaitExpr{
				FutureNames:      idents,
				AggregatorName:   SDLDollar[4].expr.(*CallExpr).Function.(*IdentifierExpr),
				AggregatorParams: SDLDollar[4].expr.(*CallExpr).ArgMap,
			}
			SDLVAL.expr.(*WaitExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.Pos(), endNode.End())
		}
	case 82:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:607
		{
			SDLVAL.exprMap = map[string]Expr{SDLDollar[1].ident.Value: SDLDollar[3].expr}
		}
	case 83:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:608
		{
			name := SDLDollar[3].ident.Value
			SDLDollar[1].exprMap[name] = SDLDollar[5].expr
			SDLVAL.exprMap = SDLDollar[1].exprMap
		}
	case 84:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:616
		{
			SDLVAL.exprList = []Expr{SDLDollar[1].expr}
		}
	case 85:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:617
		{
			SDLVAL.exprList = append(SDLDollar[1].exprList, SDLDollar[3].expr)
		}
	case 86:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:622
		{ // IF($1) ...
			endNode := Stmt(SDLDollar[3].blockStmt)
			if SDLDollar[4].stmt != nil {
				endNode = SDLDollar[4].stmt
			} // End of Else block/IfStmt
			SDLVAL.ifStmt = &IfStmt{
				NodeInfo:  NewNodeInfo(SDLDollar[1].node.(Node).Pos(), endNode.End()),
				Condition: SDLDollar[2].expr,
				Then:      SDLDollar[3].blockStmt,
				Else:      SDLDollar[4].stmt,
			}
		}
	case 87:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:635
		{
			SDLVAL.stmt = nil
		}
	case 88:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:636
		{
			SDLVAL.stmt = SDLDollar[2].ifStmt
		}
	case 89:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:637
		{
			SDLVAL.stmt = SDLDollar[2].blockStmt
		}
	case 90:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:641
		{ // DISTRIBUTE($1) ... RBRACE($6)
			SDLVAL.sampleExpr = &SampleExpr{FromExpr: SDLDollar[2].expr}
			SDLVAL.sampleExpr.NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.(Node).End())
		}
	case 91:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:647
		{
			SDLVAL.expr = nil
		}
	case 92:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:647
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 93:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:649
		{
			SDLVAL.tupleExpr = &TupleExpr{Children: append(SDLDollar[2].exprList, SDLDollar[4].expr)}
		}
	case 94:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:654
		{ // GO($1) ... BlockStmt($4)
			SDLVAL.expr = &GoExpr{Stmt: SDLDollar[2].blockStmt}
			SDLVAL.expr.(*GoExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].blockStmt.End())
		}
	case 95:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:658
		{
			SDLVAL.expr = &GoExpr{Expr: SDLDollar[2].expr}
			SDLVAL.expr.(*GoExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.End())
		}
	case 96:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:662
		{ // GO($1) ... BlockStmt($4)
			SDLVAL.expr = &GoExpr{LoopExpr: SDLDollar[2].expr, Stmt: SDLDollar[3].blockStmt}
			SDLVAL.expr.(*GoExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].blockStmt.End())
		}
	case 97:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:666
		{
			SDLVAL.expr = &GoExpr{LoopExpr: SDLDollar[2].expr, Expr: SDLDollar[3].expr}
			SDLVAL.expr.(*GoExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].expr.End())
		}
	case 98:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:675
		{
			SDLDollar[1].chainedExpr.Unchain(nil)
			SDLVAL.expr = SDLDollar[1].chainedExpr.UnchainedExpr
		}
	case 99:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:679
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 100:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:680
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 101:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:707
		{
			SDLVAL.chainedExpr = &ChainedExpr{Children: []Expr{SDLDollar[1].expr}}
		}
	case 102:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:710
		{
			SDLDollar[1].chainedExpr.Children = append(SDLDollar[1].chainedExpr.Children, SDLDollar[3].expr)
			SDLDollar[1].chainedExpr.Operators = append(SDLDollar[1].chainedExpr.Operators, SDLDollar[2].node.String())
			SDLVAL.chainedExpr = SDLDollar[1].chainedExpr
		}
	case 103:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:715
		{
			SDLDollar[1].chainedExpr.Children = append(SDLDollar[1].chainedExpr.Children, SDLDollar[3].expr)
			SDLDollar[1].chainedExpr.Operators = append(SDLDollar[1].chainedExpr.Operators, SDLDollar[2].node.String())
			SDLVAL.chainedExpr = SDLDollar[1].chainedExpr
		}
	case 104:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:722
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 105:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:724
		{
			SDLVAL.expr = &UnaryExpr{Operator: SDLDollar[1].node.String(), Right: SDLDollar[2].expr}
			SDLVAL.expr.(*UnaryExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.(Node).End())
		}
	case 106:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:729
		{
			SDLVAL.expr = &UnaryExpr{Operator: SDLDollar[1].node.String(), Right: SDLDollar[2].expr}
			SDLVAL.expr.(*UnaryExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.(Node).End())
		}
	case 107:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:737
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 108:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:738
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 109:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:742
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 110:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:743
		{
			SDLVAL.expr = SDLDollar[1].ident
		}
	case 111:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:744
		{
			SDLVAL.expr = SDLDollar[1].distributeExpr
		}
	case 112:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:745
		{
			SDLVAL.expr = SDLDollar[1].sampleExpr
		}
	case 113:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:746
		{
			SDLVAL.expr = SDLDollar[1].tupleExpr
		}
	case 114:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:747
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 115:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:748
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 116:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:749
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 117:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:752
		{
			SDLVAL.expr = SDLDollar[2].expr
		}
	case 118:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:755
		{
			// SDLlex.(*Lexer).lval)
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 119:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:759
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 120:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:760
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 121:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:761
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 122:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:762
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 123:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:766
		{ // Expression "[" Key "]"
			SDLVAL.expr = &IndexExpr{
				Receiver: SDLDollar[1].expr,
				Key:      SDLDollar[3].expr,
			}
			SDLVAL.expr.(*IndexExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), SDLDollar[4].node.End())
		}
	case 124:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:776
		{ // PrimaryExpr($1) DOT($2) IDENTIFIER($3)
			SDLVAL.expr = &MemberAccessExpr{
				Receiver: SDLDollar[1].ident,
				Member:   SDLDollar[3].ident,
			}
			SDLVAL.expr.(*MemberAccessExpr).NodeInfo = NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[3].ident.End())
		}
	case 125:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:783
		{ // PrimaryExpr($1) DOT($2) IDENTIFIER($3)
			SDLVAL.expr = &MemberAccessExpr{
				Receiver: SDLDollar[1].expr,
				Member:   SDLDollar[3].ident,
			}
			SDLVAL.expr.(*MemberAccessExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), SDLDollar[3].ident.End())
		}
	case 126:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:793
		{ // PrimaryExpr($1) LPAREN($2) ArgList($3) RPAREN($4)
			SDLVAL.expr = &CallExpr{Function: SDLDollar[1].expr}
			SDLVAL.expr.(*CallExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), SDLDollar[3].node.End())
		}
	case 127:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:797
		{ // PrimaryExpr($1) LPAREN($2) ArgList($3) RPAREN($4)
			endNode := SDLDollar[4].node.(Node) // End at RPAREN
			if len(SDLDollar[3].exprList) > 0 {
				exprList := SDLDollar[3].exprList
				endNode = exprList[len(exprList)-1].(Node) // End at last arg
			}
			SDLVAL.expr = &CallExpr{
				Function: SDLDollar[1].expr,
				ArgList:  SDLDollar[3].exprList,
			}
			SDLVAL.expr.(*CallExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), endNode.End())
		}
	case 128:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:809
		{ // PrimaryExpr($1) LPAREN($2) ArgList($3) RPAREN($4)
			endNode := SDLDollar[4].node.(Node) // End at RPAREN
			SDLVAL.expr = &CallExpr{
				Function: SDLDollar[1].expr,
				IsNamed:  true,
				ArgMap:   SDLDollar[3].exprMap,
			}
			SDLVAL.expr.(*CallExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), endNode.End())
		}
	case 129:
		SDLDollar = SDLS[SDLpt-6 : SDLpt+1]
//line grammar.y:821
		{
			SDLVAL.distributeExpr = &DistributeExpr{TotalProb: SDLDollar[2].expr, Cases: SDLDollar[4].caseExprList, Default: SDLDollar[5].expr} /* TODO: Pos */
		}
	case 130:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:827
		{
			SDLVAL.caseExprList = []*CaseExpr{}
		}
	case 131:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:828
		{
			SDLVAL.caseExprList = SDLDollar[1].caseExprList
		}
	case 132:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:832
		{
			SDLVAL.caseExprList = []*CaseExpr{SDLDollar[1].caseExpr}
		}
	case 133:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:833
		{
			SDLVAL.caseExprList = append(SDLDollar[1].caseExprList, SDLDollar[2].caseExpr)
		}
	case 134:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:837
		{
			SDLVAL.caseExpr = &CaseExpr{Condition: SDLDollar[1].expr, Body: SDLDollar[3].expr}
		}
	case 135:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:840
		{ // allow optional comma
			SDLVAL.caseExpr = &CaseExpr{Condition: SDLDollar[1].expr, Body: SDLDollar[3].expr}
		}
	case 136:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:846
		{
			SDLVAL.expr = nil
		}
	case 137:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:847
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 138:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:851
		{
			SDLVAL.expr = SDLDollar[3].expr
		}
	case 139:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:852
		{
			SDLVAL.expr = SDLDollar[3].expr
		}
	case 140:
		SDLDollar = SDLS[SDLpt-6 : SDLpt+1]
//line grammar.y:856
		{
			SDLVAL.switchStmt = &SwitchStmt{Expr: SDLDollar[2].expr, Cases: SDLDollar[4].caseStmtList, Default: SDLDollar[5].stmt} /* TODO: Pos */
		}
	case 141:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:862
		{
			SDLVAL.caseStmtList = []*CaseStmt{}
		}
	case 142:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:863
		{
			SDLVAL.caseStmtList = SDLDollar[1].caseStmtList
		}
	case 143:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:867
		{
			SDLVAL.caseStmtList = []*CaseStmt{SDLDollar[1].caseStmt}
		}
	case 144:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:868
		{
			SDLVAL.caseStmtList = append(SDLDollar[1].caseStmtList, SDLDollar[2].caseStmt)
		}
	case 145:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:872
		{
			SDLVAL.caseStmt = &CaseStmt{NodeInfo: NewNodeInfo(SDLDollar[1].expr.(Node).Pos(), SDLDollar[3].stmt.End()), Condition: SDLDollar[1].expr, Body: SDLDollar[3].stmt}
		}
	case 146:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:876
		{
			SDLVAL.stmt = nil
		}
	case 147:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:877
		{
			SDLVAL.stmt = SDLDollar[1].stmt
		}
	case 148:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:881
		{
			SDLVAL.stmt = SDLDollar[3].stmt
		}
	case 149:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:885
		{
			SDLVAL.stmt = &ExprStmt{NodeInfo: NewNodeInfo(SDLDollar[1].expr.(Node).Pos(), SDLDollar[1].expr.(Node).End()), Expression: SDLDollar[1].expr}
		}
	case 150:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:886
		{
			SDLVAL.stmt = &ExprStmt{NodeInfo: NewNodeInfo(SDLDollar[1].expr.(Node).Pos(), SDLDollar[1].expr.(Node).End()), Expression: SDLDollar[1].expr}
		}
	}
	goto SDLstack /* stack new state and value */
}
