// Code generated by goyacc -o parser.go -p SDL grammar.y. DO NOT EDIT.

//line grammar.y:2
package parser

import __yyfmt__ "fmt"

//line grammar.y:2

import (
	// "reflect"
	"fmt"
	"io"
	"log"
)

// Function to be called by SDLParse on error.
// Needs access to the lexer passed via %parse-param.
func yyerror(yyl SDLLexer, msg string) {
	lexer := yyl.(LexerInterface)
	// line, col := lexer.Position()
	// log.Println("YYERROR MSG = ", msg)
	// errMsg := fmt.Sprintf("Error at Line %d, Col %d, Near ('%s'): %s", line, col, /* TokenString(lexer.LastToken()),*/ lexer.Text(), msg) // Added TokenString helper call
	lexer.Error(msg)
}

func yyerrok(lexer SDLLexer) {
	log.Println("Error here... not sure how to recover")
	///ErrFlag = 0
}

//line grammar.y:30
type SDLSymType struct {
	yys int
	// Basic types from lexer
	sval string // Holds raw string values like identifiers, literal content

	// AST Nodes (using pointers) - these should have NodeInfo
	file           *FileDecl
	componentDecl  *ComponentDecl
	systemDecl     *SystemDecl
	aggregatorDecl *AggregatorDecl
	node           Node // Generic interface for lists and for accessing NodeInfo
	// tokenNode   TokenNode // Generic interface for lists and for accessing NodeInfo
	expr         Expr
	chainedExpr  *ChainedExpr
	stmt         Stmt
	typeDecl     *TypeDecl
	paramDecl    *ParamDecl
	usesDecl     *UsesDecl
	methodDef    *MethodDecl
	instanceDecl *InstanceDecl
	analyzeDecl  *AnalyzeDecl
	expectBlock  *ExpectationsDecl
	expectStmt   *ExpectStmt
	blockStmt    *BlockStmt
	ifStmt       *IfStmt

	distributeExpr *DistributeExpr
	caseExpr       *CaseExpr

	switchStmt *SwitchStmt
	caseStmt   *CaseStmt

	tupleExpr   *TupleExpr
	goExpr      *GoExpr
	forStmt     *ForStmt
	assignStmt  *AssignmentStmt
	optionsDecl *OptionsDecl
	enumDecl    *EnumDecl
	importDecl  *ImportDecl
	waitExpr    *WaitExpr
	delayStmt   *DelayStmt
	sampleExpr  *SampleExpr

	// Slices for lists
	nodeList               []Node
	caseExprList           []*CaseExpr
	typeDeclList           []*TypeDecl
	caseStmtList           []*CaseStmt
	importDeclList         []*ImportDecl
	compBodyItem           ComponentDeclBodyItem
	compBodyItemList       []ComponentDeclBodyItem
	sysBodyItemList        []SystemDeclBodyItem
	paramList              []*ParamDecl
	assignList             []*AssignmentStmt
	exprList               []Expr
	exprMap                map[string]Expr
	stmtList               []Stmt
	ident                  *IdentifierExpr
	identList              []*IdentifierExpr
	distributeExprCaseList []*CaseExpr
	expectStmtList         []*ExpectStmt
	methodSigItemList      []*MethodDecl

	// Add field to store position for simple tokens if needed
	// posInfo     NodeInfo
}

const SYSTEM = 57346
const USES = 57347
const AGGREGATOR = 57348
const METHOD = 57349
const ANALYZE = 57350
const EXPECT = 57351
const LET = 57352
const IF = 57353
const ELSE = 57354
const SAMPLE = 57355
const DISTRIBUTE = 57356
const DEFAULT = 57357
const RETURN = 57358
const DELAY = 57359
const WAIT = 57360
const GO = 57361
const GOBATCH = 57362
const USING = 57363
const LOG = 57364
const SWITCH = 57365
const CASE = 57366
const FOR = 57367
const USE = 57368
const NATIVE = 57369
const LSQUARE = 57370
const RSQUARE = 57371
const LBRACE = 57372
const RBRACE = 57373
const OPTIONS = 57374
const ENUM = 57375
const COMPONENT = 57376
const PARAM = 57377
const IMPORT = 57378
const FROM = 57379
const AS = 57380
const ASSIGN = 57381
const COLON = 57382
const LPAREN = 57383
const RPAREN = 57384
const COMMA = 57385
const DOT = 57386
const ARROW = 57387
const LET_ASSIGN = 57388
const SEMICOLON = 57389
const INT = 57390
const FLOAT = 57391
const BOOL = 57392
const STRING = 57393
const DURATION = 57394
const INT_LITERAL = 57395
const FLOAT_LITERAL = 57396
const STRING_LITERAL = 57397
const BOOL_LITERAL = 57398
const DURATION_LITERAL = 57399
const IDENTIFIER = 57400
const OR = 57401
const AND = 57402
const EQ = 57403
const NEQ = 57404
const LT = 57405
const LTE = 57406
const GT = 57407
const GTE = 57408
const PLUS = 57409
const MUL = 57410
const DIV = 57411
const MOD = 57412
const DUAL_OP = 57413
const BINARY_NC_OP = 57414
const BINARY_OP = 57415
const UNARY_OP = 57416
const MINUS = 57417
const UMINUS = 57418

var SDLToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SYSTEM",
	"USES",
	"AGGREGATOR",
	"METHOD",
	"ANALYZE",
	"EXPECT",
	"LET",
	"IF",
	"ELSE",
	"SAMPLE",
	"DISTRIBUTE",
	"DEFAULT",
	"RETURN",
	"DELAY",
	"WAIT",
	"GO",
	"GOBATCH",
	"USING",
	"LOG",
	"SWITCH",
	"CASE",
	"FOR",
	"USE",
	"NATIVE",
	"LSQUARE",
	"RSQUARE",
	"LBRACE",
	"RBRACE",
	"OPTIONS",
	"ENUM",
	"COMPONENT",
	"PARAM",
	"IMPORT",
	"FROM",
	"AS",
	"ASSIGN",
	"COLON",
	"LPAREN",
	"RPAREN",
	"COMMA",
	"DOT",
	"ARROW",
	"LET_ASSIGN",
	"SEMICOLON",
	"INT",
	"FLOAT",
	"BOOL",
	"STRING",
	"DURATION",
	"INT_LITERAL",
	"FLOAT_LITERAL",
	"STRING_LITERAL",
	"BOOL_LITERAL",
	"DURATION_LITERAL",
	"IDENTIFIER",
	"OR",
	"AND",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"PLUS",
	"MUL",
	"DIV",
	"MOD",
	"DUAL_OP",
	"BINARY_NC_OP",
	"BINARY_OP",
	"UNARY_OP",
	"MINUS",
	"UMINUS",
}

var SDLStatenames = [...]string{}

const SDLEofCode = 1
const SDLErrCode = 2
const SDLInitialStackSize = 16

//line grammar.y:917
// --- Go Code Section ---

// Interface for the lexer required by the parser.
type LexerInterface interface {
	Lex(lval *SDLSymType) int
	Error(s string)
	Pos() int                  // Start byte position of the last token read
	End() int                  // End byte position of the last token read
	Text() string              // Text of the last token read
	Position() (line, col int) // Added: Get line/col of last token start
	LastToken() int            // Added: Get the token code that was just lexed
}

// Parse takes an input stream and attempts to parse it according to the SDL grammar. 22222
// It returns the root of the Abstract Syntax Tree (*FileDecl) if successful, or an error.
func Parse(input io.Reader) (*Lexer, *FileDecl, error) {
	// Reset global result before parsing
	lexer := NewLexer(input)
	// Set yyDebug = 3 for verbose parser debugging output
	// yyDebug = 3
	resultCode := SDLParse(lexer) // Call the LALR parser generated by goyacc

	if resultCode != 0 {
		// A syntax error occurred. The lexer's Error method should have been called
		// and stored the error message.
		if lexer.lastError != nil {
			return lexer, nil, lexer.lastError
		}
		// Fallback error message if lexer didn't store one
		return lexer, nil, fmt.Errorf("syntax error near byte %d (Line %d, Col %d)", lexer.location.Pos, lexer.location.Line, lexer.location.Col)
	}

	// Parsing succeeded
	if lexer.parseResult == nil {
		// This indicates a potential issue with the grammar's top rule action
		return lexer, nil, fmt.Errorf("parsing finished successfully, but no AST result was produced")
	}

	return lexer, lexer.parseResult, nil
}

// The parser expects the lexer variable to be named yyLex.
// We can satisfy this by creating a global or passing it via SDLParseWithLexer.
// Using SDLParseWithLexer is cleaner.

// Example main function (optional, for standalone testing)
/*
func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: parser <input_file>")
		return
	}
	filePath := os.Args[1]
	file, err := os.Open(filePath)
	if err != nil {
		fmt.Printf("Error opening file %s: %v\n", filePath, err)
		return
	}
	defer file.Close()

	astRoot, err := Parse(file)
	if err != nil {
		fmt.Printf("Parsing failed: %v\n", err)
		// Error message should ideally include line/column from lexer
	} else {
		fmt.Println("Parsing successful!")
		// Print the AST (implement String() methods for AST nodes for nice output)
		fmt.Println(astRoot.String())
	}
}
*/

//line yacctab:1
var SDLExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 65,
	41, 114,
	-2, 155,
}

const SDLPrivate = 57344

const SDLLast = 508

var SDLAct = [...]int16{
	202, 54, 222, 220, 187, 212, 59, 125, 62, 122,
	118, 186, 201, 101, 140, 30, 44, 96, 90, 89,
	159, 92, 160, 74, 120, 121, 119, 34, 153, 223,
	151, 151, 233, 191, 102, 72, 181, 177, 176, 156,
	154, 31, 65, 93, 73, 66, 91, 150, 150, 106,
	105, 38, 19, 29, 25, 23, 97, 22, 84, 85,
	86, 87, 88, 77, 36, 14, 107, 55, 115, 126,
	128, 129, 130, 252, 9, 248, 239, 231, 207, 123,
	124, 174, 136, 135, 241, 157, 114, 142, 12, 143,
	138, 139, 141, 15, 16, 13, 133, 11, 218, 143,
	131, 217, 218, 143, 206, 205, 261, 149, 3, 135,
	152, 260, 97, 145, 146, 244, 155, 158, 204, 203,
	112, 162, 163, 65, 26, 73, 66, 111, 179, 161,
	27, 148, 43, 172, 256, 175, 243, 166, 240, 65,
	180, 73, 66, 147, 224, 190, 132, 170, 40, 250,
	164, 165, 182, 245, 189, 188, 184, 28, 192, 20,
	98, 49, 183, 50, 196, 251, 21, 247, 144, 103,
	178, 167, 195, 69, 72, 104, 39, 64, 35, 213,
	214, 33, 208, 51, 73, 215, 193, 194, 48, 219,
	13, 48, 72, 113, 20, 32, 24, 216, 108, 15,
	209, 185, 134, 18, 232, 225, 237, 226, 234, 229,
	198, 47, 213, 230, 6, 117, 227, 238, 228, 199,
	90, 89, 200, 242, 61, 74, 120, 121, 246, 235,
	236, 37, 78, 249, 210, 211, 137, 171, 221, 65,
	253, 73, 66, 57, 110, 46, 255, 254, 91, 169,
	257, 258, 45, 259, 99, 100, 65, 116, 73, 66,
	84, 85, 86, 87, 88, 173, 90, 89, 81, 75,
	83, 74, 120, 121, 82, 76, 80, 79, 60, 58,
	56, 123, 124, 197, 17, 5, 10, 52, 94, 95,
	90, 89, 41, 42, 91, 74, 120, 121, 90, 89,
	127, 8, 7, 4, 109, 2, 84, 85, 86, 87,
	88, 77, 1, 0, 0, 0, 0, 0, 91, 0,
	0, 0, 0, 0, 0, 0, 91, 123, 124, 0,
	84, 85, 86, 87, 88, 77, 0, 0, 84, 85,
	86, 87, 88, 77, 90, 89, 0, 0, 0, 0,
	0, 123, 124, 0, 0, 0, 0, 0, 0, 123,
	124, 64, 69, 0, 90, 89, 0, 68, 70, 74,
	0, 0, 91, 0, 71, 0, 67, 0, 0, 0,
	0, 72, 168, 0, 84, 85, 86, 87, 88, 77,
	0, 0, 91, 0, 0, 0, 0, 0, 63, 0,
	0, 0, 0, 0, 84, 85, 86, 87, 88, 77,
	64, 69, 0, 90, 89, 0, 68, 70, 74, 0,
	0, 0, 0, 71, 0, 67, 0, 0, 0, 0,
	72, 53, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 91, 0, 0, 0, 0, 0, 63, 0, 0,
	0, 0, 0, 84, 85, 86, 87, 88, 77, 64,
	69, 0, 90, 89, 0, 68, 70, 74, 0, 0,
	0, 0, 71, 0, 67, 0, 0, 0, 0, 72,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	91, 0, 0, 0, 0, 0, 63, 0, 0, 0,
	0, 0, 84, 85, 86, 87, 88, 77,
}

var SDLPact = [...]int16{
	-1000, -1000, 61, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -6, 160, -1, -3, 166, -4, 87, -1000, 119,
	-5, -17, 165, 151, -1000, 148, 9, -6, -7, 146,
	-1000, 107, 156, -1000, 400, -15, -1000, -1000, -1000, 153,
	-24, 138, 156, -1000, -1000, -1000, -1000, -1000, -8, -9,
	-17, 125, 167, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -15, -1000, -1000, 277, 253, 277,
	277, 277, -1000, 105, -15, 174, -1000, 65, -1000, -1000,
	-1000, -1000, 38, -1000, -1000, -1000, -1000, -1000, -1000, 277,
	277, 277, 56, -1000, 137, 153, -1000, -1000, -17, 101,
	88, -1000, -10, -1000, -1000, -11, -18, 144, -1000, -1000,
	-1000, -1000, -1000, -19, 46, 449, -53, -1000, -1000, -1000,
	5, 277, 105, 285, 285, -1000, -1000, -1000, 144, -1000,
	141, 351, 207, 60, 277, -20, -21, 140, -1000, -1000,
	85, 98, -1000, -22, -1000, -1000, -1000, -10, -24, 117,
	173, -10, 116, 277, 104, -1000, -25, 277, -1000, 285,
	285, -1000, -1000, 5, -1000, -1000, 198, 277, -1000, -1000,
	76, 62, -1000, 39, 331, 171, -1000, -1000, 277, 277,
	-1000, -1000, -1000, -1000, 277, -10, 59, -1000, 277, -1000,
	-29, 103, -1000, -1000, -1000, -1000, -1000, -1000, 162, 194,
	277, -1000, 32, 277, -1000, -26, -1000, 277, -1000, -1000,
	191, 277, -1000, 31, 96, -1000, 55, -1000, -10, -1000,
	94, 72, -1000, 114, -29, -1000, -1000, 136, -1000, 30,
	-1000, 449, -1000, 110, -1000, 134, -1000, 28, -1000, 277,
	-1000, -1000, -1000, -1000, -29, 277, 92, -1000, 449, -1000,
	277, -1000, 277, 68, -1000, -1000, -1000, -1000, -1000, 63,
	-1000, -1000,
}

var SDLPgo = [...]int16{
	0, 312, 305, 304, 303, 211, 302, 301, 132, 293,
	292, 17, 289, 288, 287, 74, 286, 21, 203, 285,
	284, 1, 283, 67, 280, 279, 278, 277, 8, 27,
	276, 0, 26, 9, 275, 7, 274, 270, 269, 268,
	10, 257, 16, 13, 255, 254, 4, 11, 252, 245,
	15, 244, 243, 2, 238, 3, 6, 14, 237, 236,
	5, 235, 234, 232, 230, 229, 224, 12, 222, 219,
	218, 216, 215,
}

var SDLR1 = [...]int8{
	0, 1, 2, 2, 2, 2, 4, 4, 4, 4,
	4, 15, 5, 5, 16, 17, 17, 19, 20, 20,
	18, 18, 50, 50, 13, 13, 12, 12, 11, 11,
	10, 10, 9, 9, 8, 8, 8, 8, 42, 42,
	42, 46, 46, 46, 47, 47, 48, 48, 49, 45,
	45, 44, 44, 43, 43, 6, 7, 14, 14, 3,
	3, 3, 51, 51, 55, 55, 54, 54, 53, 29,
	29, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	28, 52, 23, 25, 25, 26, 40, 40, 58, 58,
	57, 57, 56, 22, 22, 22, 27, 59, 59, 30,
	72, 72, 72, 72, 31, 31, 31, 41, 41, 41,
	32, 32, 32, 33, 33, 38, 38, 38, 38, 38,
	38, 38, 38, 39, 34, 34, 34, 34, 34, 37,
	36, 36, 35, 35, 35, 63, 62, 62, 61, 61,
	60, 60, 65, 65, 64, 64, 66, 69, 69, 68,
	68, 67, 71, 71, 70, 24, 24,
}

var SDLR2 = [...]int8{
	0, 1, 0, 2, 2, 2, 1, 1, 1, 1,
	1, 4, 6, 5, 5, 1, 3, 4, 1, 3,
	1, 3, 4, 5, 0, 1, 1, 2, 1, 2,
	0, 1, 1, 2, 1, 1, 1, 1, 3, 4,
	5, 1, 3, 4, 1, 3, 3, 6, 3, 0,
	1, 1, 3, 2, 4, 5, 3, 0, 2, 1,
	1, 1, 3, 6, 0, 1, 1, 3, 3, 0,
	2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 3, 4, 2, 2, 2, 2, 4, 3, 5,
	1, 3, 4, 0, 2, 2, 2, 0, 1, 5,
	2, 2, 3, 3, 1, 1, 1, 1, 3, 3,
	1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 1, 1, 1, 1, 1, 4,
	3, 3, 3, 4, 4, 6, 0, 1, 1, 2,
	3, 4, 0, 1, 3, 4, 6, 0, 1, 1,
	2, 3, 0, 1, 3, 1, 1,
}

var SDLChk = [...]int16{
	-1000, -1, -2, 47, -4, -19, -5, -6, -7, -15,
	-16, 36, 27, 34, 4, 32, 33, -20, -18, 58,
	34, 6, 58, 58, 30, 58, 37, 43, 38, 58,
	-50, 58, 30, 30, -29, 30, 55, -18, 58, 30,
	41, -10, -9, -8, -42, -48, -49, -5, 35, 5,
	7, 27, -14, 31, -21, -23, -24, -52, -25, -56,
	-26, -66, -28, 47, 10, -35, -40, 25, 16, 11,
	17, 23, 30, -33, 18, -38, -34, 58, -63, -27,
	-30, -39, -36, -37, 53, 54, 55, 56, 57, 14,
	13, 41, -17, 58, -13, -12, -11, -42, 7, -45,
	-44, -43, 58, 31, -8, 58, 58, -50, 31, -3,
	-51, -15, -23, 26, -17, -31, -41, -72, -40, -32,
	19, 20, -33, 74, 75, -35, -31, 47, -31, -31,
	-31, -29, 41, -17, 28, 44, 44, -59, -31, -31,
	-57, -31, 31, 43, 31, -11, -50, 42, 43, -46,
	58, 41, -46, 39, 58, -28, 58, 39, -21, 73,
	75, -28, -31, -31, -32, -32, -28, 30, 31, 42,
	-57, -58, -31, 58, 21, -31, 58, 58, 30, 43,
	42, 58, -46, -43, 39, 28, -47, -46, 39, -31,
	41, 58, -31, -32, -32, -28, -31, -22, 12, -69,
	-68, -67, -31, 43, 42, 43, 42, 39, -35, 29,
	-62, -61, -60, -31, -31, -31, -47, 42, 43, -31,
	-55, -54, -53, 58, 41, -56, -28, -71, -70, 15,
	-67, 45, -31, 58, -31, -65, -64, 15, -60, 45,
	42, 29, -46, 42, 43, 39, -55, 31, 45, -21,
	39, 31, 45, -31, -53, -31, 42, -21, -31, -31,
	43, 43,
}

var SDLDef = [...]int16{
	2, -2, 1, 3, 4, 5, 6, 7, 8, 9,
	10, 0, 0, 0, 0, 0, 0, 0, 18, 20,
	0, 0, 0, 0, 69, 0, 0, 0, 0, 0,
	56, 0, 30, 57, 0, 0, 17, 19, 21, 24,
	49, 0, 31, 32, 34, 35, 36, 37, 0, 0,
	0, 0, 0, 11, 70, 71, 72, 73, 74, 75,
	76, 77, 78, 79, 0, -2, 156, 0, 0, 0,
	0, 0, 69, 0, 0, 113, 115, 116, 117, 118,
	119, 120, 121, 122, 124, 125, 126, 127, 128, 97,
	0, 0, 0, 15, 0, 25, 26, 28, 0, 0,
	50, 51, 0, 13, 33, 0, 0, 0, 55, 58,
	59, 60, 61, 0, 0, 0, 104, 105, 106, 107,
	0, 0, 110, 0, 0, 114, 83, 84, 0, 85,
	0, 0, 0, 86, 0, 0, 0, 0, 98, 96,
	0, 90, 14, 0, 12, 27, 29, 22, 0, 53,
	41, 0, 38, 0, 46, 48, 0, 0, 81, 0,
	0, 100, 101, 0, 111, 112, 93, 147, 80, 132,
	0, 0, 90, 116, 0, 0, 130, 131, 136, 0,
	123, 16, 23, 52, 0, 0, 0, 44, 0, 39,
	64, 62, 82, 108, 109, 102, 103, 92, 0, 152,
	148, 149, 0, 0, 133, 0, 134, 0, 87, 129,
	142, 137, 138, 0, 91, 54, 0, 42, 0, 40,
	0, 65, 66, 0, 64, 94, 95, 0, 153, 0,
	150, 0, 91, 0, 88, 0, 143, 0, 139, 0,
	99, 43, 45, 47, 0, 0, 0, 146, 0, 151,
	0, 135, 0, 140, 67, 68, 63, 154, 89, 144,
	141, 145,
}

var SDLTok1 = [...]int8{
	1,
}

var SDLTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76,
}

var SDLTok3 = [...]int8{
	0,
}

var SDLErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	SDLDebug        = 0
	SDLErrorVerbose = false
)

type SDLLexer interface {
	Lex(lval *SDLSymType) int
	Error(s string)
}

type SDLParser interface {
	Parse(SDLLexer) int
	Lookahead() int
}

type SDLParserImpl struct {
	lval  SDLSymType
	stack [SDLInitialStackSize]SDLSymType
	char  int
}

func (p *SDLParserImpl) Lookahead() int {
	return p.char
}

func SDLNewParser() SDLParser {
	return &SDLParserImpl{}
}

const SDLFlag = -1000

func SDLTokname(c int) string {
	if c >= 1 && c-1 < len(SDLToknames) {
		if SDLToknames[c-1] != "" {
			return SDLToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func SDLStatname(s int) string {
	if s >= 0 && s < len(SDLStatenames) {
		if SDLStatenames[s] != "" {
			return SDLStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func SDLErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !SDLErrorVerbose {
		return "syntax error"
	}

	for _, e := range SDLErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + SDLTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(SDLPact[state])
	for tok := TOKSTART; tok-1 < len(SDLToknames); tok++ {
		if n := base + tok; n >= 0 && n < SDLLast && int(SDLChk[int(SDLAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if SDLDef[state] == -2 {
		i := 0
		for SDLExca[i] != -1 || int(SDLExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; SDLExca[i] >= 0; i += 2 {
			tok := int(SDLExca[i])
			if tok < TOKSTART || SDLExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if SDLExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += SDLTokname(tok)
	}
	return res
}

func SDLlex1(lex SDLLexer, lval *SDLSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(SDLTok1[0])
		goto out
	}
	if char < len(SDLTok1) {
		token = int(SDLTok1[char])
		goto out
	}
	if char >= SDLPrivate {
		if char < SDLPrivate+len(SDLTok2) {
			token = int(SDLTok2[char-SDLPrivate])
			goto out
		}
	}
	for i := 0; i < len(SDLTok3); i += 2 {
		token = int(SDLTok3[i+0])
		if token == char {
			token = int(SDLTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(SDLTok2[1]) /* unknown char */
	}
	if SDLDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", SDLTokname(token), uint(char))
	}
	return char, token
}

func SDLParse(SDLlex SDLLexer) int {
	return SDLNewParser().Parse(SDLlex)
}

func (SDLrcvr *SDLParserImpl) Parse(SDLlex SDLLexer) int {
	var SDLn int
	var SDLVAL SDLSymType
	var SDLDollar []SDLSymType
	_ = SDLDollar // silence set and not used
	SDLS := SDLrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	SDLstate := 0
	SDLrcvr.char = -1
	SDLtoken := -1 // SDLrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		SDLstate = -1
		SDLrcvr.char = -1
		SDLtoken = -1
	}()
	SDLp := -1
	goto SDLstack

ret0:
	return 0

ret1:
	return 1

SDLstack:
	/* put a state and value onto the stack */
	if SDLDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", SDLTokname(SDLtoken), SDLStatname(SDLstate))
	}

	SDLp++
	if SDLp >= len(SDLS) {
		nyys := make([]SDLSymType, len(SDLS)*2)
		copy(nyys, SDLS)
		SDLS = nyys
	}
	SDLS[SDLp] = SDLVAL
	SDLS[SDLp].yys = SDLstate

SDLnewstate:
	SDLn = int(SDLPact[SDLstate])
	if SDLn <= SDLFlag {
		goto SDLdefault /* simple state */
	}
	if SDLrcvr.char < 0 {
		SDLrcvr.char, SDLtoken = SDLlex1(SDLlex, &SDLrcvr.lval)
	}
	SDLn += SDLtoken
	if SDLn < 0 || SDLn >= SDLLast {
		goto SDLdefault
	}
	SDLn = int(SDLAct[SDLn])
	if int(SDLChk[SDLn]) == SDLtoken { /* valid shift */
		SDLrcvr.char = -1
		SDLtoken = -1
		SDLVAL = SDLrcvr.lval
		SDLstate = SDLn
		if Errflag > 0 {
			Errflag--
		}
		goto SDLstack
	}

SDLdefault:
	/* default state action */
	SDLn = int(SDLDef[SDLstate])
	if SDLn == -2 {
		if SDLrcvr.char < 0 {
			SDLrcvr.char, SDLtoken = SDLlex1(SDLlex, &SDLrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if SDLExca[xi+0] == -1 && int(SDLExca[xi+1]) == SDLstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			SDLn = int(SDLExca[xi+0])
			if SDLn < 0 || SDLn == SDLtoken {
				break
			}
		}
		SDLn = int(SDLExca[xi+1])
		if SDLn < 0 {
			goto ret0
		}
	}
	if SDLn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			SDLlex.Error(SDLErrorMessage(SDLstate, SDLtoken))
			Nerrs++
			if SDLDebug >= 1 {
				__yyfmt__.Printf("%s", SDLStatname(SDLstate))
				__yyfmt__.Printf(" saw %s\n", SDLTokname(SDLtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for SDLp >= 0 {
				SDLn = int(SDLPact[SDLS[SDLp].yys]) + SDLErrCode
				if SDLn >= 0 && SDLn < SDLLast {
					SDLstate = int(SDLAct[SDLn]) /* simulate a shift of "error" */
					if int(SDLChk[SDLstate]) == SDLErrCode {
						goto SDLstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if SDLDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", SDLS[SDLp].yys)
				}
				SDLp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if SDLDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", SDLTokname(SDLtoken))
			}
			if SDLtoken == SDLEofCode {
				goto ret1
			}
			SDLrcvr.char = -1
			SDLtoken = -1
			goto SDLnewstate /* try again in the same state */
		}
	}

	/* reduction by production SDLn */
	if SDLDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", SDLn, SDLStatname(SDLstate))
	}

	SDLnt := SDLn
	SDLpt := SDLp
	_ = SDLpt // guard against "declared and not used"

	SDLp -= int(SDLR2[SDLn])
	// SDLp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if SDLp+1 >= len(SDLS) {
		nyys := make([]SDLSymType, len(SDLS)*2)
		copy(nyys, SDLS)
		SDLS = nyys
	}
	SDLVAL = SDLS[SDLp+1]

	/* consult goto table to find next state */
	SDLn = int(SDLR1[SDLn])
	SDLg := int(SDLPgo[SDLn])
	SDLj := SDLg + SDLS[SDLp].yys + 1

	if SDLj >= SDLLast {
		SDLstate = int(SDLAct[SDLg])
	} else {
		SDLstate = int(SDLAct[SDLj])
		if int(SDLChk[SDLstate]) != -SDLn {
			SDLstate = int(SDLAct[SDLg])
		}
	}
	// dummy call; replaced with literal code
	switch SDLnt {

	case 1:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:183
		{
			ni := NodeInfo{}
			if len(SDLDollar[1].nodeList) > 0 {
				ni.StartPos = SDLDollar[1].nodeList[0].Pos()
				ni.StopPos = SDLDollar[1].nodeList[len(SDLDollar[1].nodeList)-1].End()
			}
			SDLlex.(*Lexer).parseResult = &FileDecl{NodeInfo: ni, Declarations: SDLDollar[1].nodeList}
			// $$ = &File{NodeInfo: ni, Declarations: $1}
		}
	case 2:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:195
		{
			SDLVAL.nodeList = []Node{}
		}
	case 3:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:196
		{
			SDLVAL.nodeList = SDLDollar[1].nodeList
		}
	case 4:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:197
		{
			SDLVAL.nodeList = append(SDLDollar[1].nodeList, SDLDollar[2].node)
		}
	case 5:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:200
		{
			for _, imp := range SDLDollar[2].importDeclList {
				SDLDollar[1].nodeList = append(SDLDollar[1].nodeList, imp)
			}
			SDLVAL.nodeList = SDLDollar[1].nodeList
		}
	case 6:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:209
		{
			SDLVAL.node = SDLDollar[1].componentDecl
		}
	case 7:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:210
		{
			SDLVAL.node = SDLDollar[1].systemDecl
		}
	case 8:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:211
		{
			SDLVAL.node = SDLDollar[1].aggregatorDecl
		}
	case 9:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:212
		{
			SDLVAL.node = SDLDollar[1].optionsDecl
		}
	case 10:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:213
		{
			SDLVAL.node = SDLDollar[1].enumDecl
		}
	case 11:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:217
		{ // OPTIONS ($1) LBRACE ($2) StmtList ($3) RBRACE ($4)
			// Assume OPTIONS token itself doesn't carry complex NodeInfo from lexer for this example.
			// Span from LBRACE to RBRACE for body. If StmtList is empty, Body.NodeInfo might be tricky.
			/*
			   bodyStart := $2.(Node).Pos() // Position of LBRACE (assuming lexer returns it as Node)
			   bodyEnd := $4.(Node).Pos()   // Position of RBRACE (actually its start, use .End() for full span)
			   if len($3) > 0 { // If StmtList is not empty
			       bodyStart = $3[0].Pos()
			       bodyEnd = $3[len($3)-1].End()
			   }
			*/
			SDLVAL.optionsDecl = &OptionsDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[4].node.(Node).End()), // Pos of OPTIONS, End of RBRACE
				Body: &BlockStmt{
					NodeInfo:   NewNodeInfo(SDLDollar[2].node.(Node).Pos(), SDLDollar[4].node.(Node).End()),
					Statements: SDLDollar[3].stmtList,
				},
			}
		}
	case 12:
		SDLDollar = SDLS[SDLpt-6 : SDLpt+1]
//line grammar.y:239
		{ // COMPONENT($1) ... RBRACE($5)
			SDLVAL.componentDecl = &ComponentDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[6].node.(Node).End()),
				Name:     SDLDollar[3].ident,
				Body:     SDLDollar[5].compBodyItemList,
				IsNative: true,
			}
		}
	case 13:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:247
		{ // COMPONENT($1) ... RBRACE($5)
			SDLVAL.componentDecl = &ComponentDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[5].node.(Node).End()),
				Name:     SDLDollar[2].ident,
				Body:     SDLDollar[4].compBodyItemList,
			}
		}
	case 14:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:257
		{ // ENUM($1) IDENTIFIER($2) ... RBRACE($5)
			SDLVAL.enumDecl = &EnumDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[5].node.(Node).End()),
				Name:     SDLDollar[2].ident, // $2 is an IdentifierExpr from lexer, has Pos/End
				Values:   SDLDollar[4].identList,
			}
		}
	case 15:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:267
		{
			SDLVAL.identList = []*IdentifierExpr{SDLDollar[1].ident}
		}
	case 16:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:268
		{
			SDLVAL.identList = append(SDLDollar[1].identList, SDLDollar[3].ident)
		}
	case 17:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:272
		{ // IMPORT($1) STRING_LITERAL($2)
			path := SDLDollar[4].expr.(*LiteralExpr)
			for _, imp := range SDLDollar[2].importDeclList {
				imp.Path = path
			}
			SDLVAL.importDeclList = SDLDollar[2].importDeclList
		}
	case 18:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:281
		{
			SDLVAL.importDeclList = []*ImportDecl{SDLDollar[1].importDecl}
		}
	case 19:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:282
		{
			SDLVAL.importDeclList = append(SDLVAL.importDeclList, SDLDollar[3].importDecl)
		}
	case 20:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:285
		{
			SDLVAL.importDecl = &ImportDecl{ImportedItem: SDLDollar[1].ident, Alias: SDLDollar[1].ident}
		}
	case 21:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:286
		{
			SDLVAL.importDecl = &ImportDecl{ImportedItem: SDLDollar[1].ident, Alias: SDLDollar[3].ident}
		}
	case 22:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:290
		{ // METHOD($1) ... BlockStmt($6)
			SDLVAL.methodDef = &MethodDecl{
				NodeInfo:   NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[4].node.End()),
				Name:       SDLDollar[1].ident,
				Parameters: SDLDollar[3].paramList,
			}
		}
	case 23:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:297
		{ // METHOD($1) ... BlockStmt($8)
			SDLVAL.methodDef = &MethodDecl{
				NodeInfo:   NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[5].typeDecl.End()),
				Name:       SDLDollar[1].ident,
				Parameters: SDLDollar[3].paramList,
				ReturnType: SDLDollar[5].typeDecl,
			}
		}
	case 24:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:308
		{
			SDLVAL.compBodyItemList = []ComponentDeclBodyItem{}
		}
	case 25:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:309
		{
			SDLVAL.compBodyItemList = SDLDollar[1].compBodyItemList
		}
	case 26:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:313
		{
			SDLVAL.compBodyItemList = []ComponentDeclBodyItem{SDLDollar[1].compBodyItem}
		}
	case 27:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:314
		{
			SDLVAL.compBodyItemList = append(SDLDollar[1].compBodyItemList, SDLDollar[2].compBodyItem)
		}
	case 28:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:318
		{
			SDLVAL.compBodyItem = SDLDollar[1].paramDecl
		}
	case 29:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:319
		{
			SDLVAL.compBodyItem = SDLDollar[2].methodDef
		}
	case 30:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:324
		{
			SDLVAL.compBodyItemList = []ComponentDeclBodyItem{}
		}
	case 31:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:325
		{
			SDLVAL.compBodyItemList = SDLDollar[1].compBodyItemList
		}
	case 32:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:329
		{
			SDLVAL.compBodyItemList = []ComponentDeclBodyItem{SDLDollar[1].compBodyItem}
		}
	case 33:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:330
		{
			SDLVAL.compBodyItemList = append(SDLDollar[1].compBodyItemList, SDLDollar[2].compBodyItem)
		}
	case 34:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:334
		{
			SDLVAL.compBodyItem = SDLDollar[1].paramDecl
		}
	case 35:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:335
		{
			SDLVAL.compBodyItem = SDLDollar[1].usesDecl
		}
	case 36:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:336
		{
			SDLVAL.compBodyItem = SDLDollar[1].methodDef
		}
	case 37:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:337
		{
			SDLVAL.compBodyItem = SDLDollar[1].componentDecl
		}
	case 38:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:341
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].typeDecl.End()),
				Name:     SDLDollar[2].ident,
				TypeDecl: SDLDollar[3].typeDecl, // TypeDecl also needs to have NodeInfo
			}
		}
	case 39:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:348
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo:     NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[4].expr.End()),
				Name:         SDLDollar[2].ident,
				DefaultValue: SDLDollar[4].expr,
			}
		}
	case 40:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:355
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo:     NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[5].expr.End()),
				Name:         SDLDollar[2].ident,
				TypeDecl:     SDLDollar[3].typeDecl,
				DefaultValue: SDLDollar[5].expr,
			}
		}
	case 41:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:367
		{
			identNode := SDLDollar[1].ident
			SDLVAL.typeDecl = &TypeDecl{
				NodeInfo: identNode.NodeInfo,
				Name:     identNode.Value,
			}
		}
	case 42:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:374
		{ // Tuple type
			if len(SDLDollar[2].typeDeclList) == 1 {
				SDLVAL.typeDecl = SDLDollar[2].typeDeclList[0]
			} else {
				SDLVAL.typeDecl = &TypeDecl{
					NodeInfo: NewNodeInfo(SDLDollar[1].node.Pos(), SDLDollar[3].node.Pos()),
					Name:     "Tuple",
					Args:     SDLDollar[2].typeDeclList,
				}
			}
		}
	case 43:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:385
		{
			identNode := SDLDollar[1].ident
			SDLVAL.typeDecl = &TypeDecl{
				NodeInfo: identNode.NodeInfo,
				Name:     identNode.Value,
				Args:     SDLDollar[3].typeDeclList,
			}
		}
	case 44:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:401
		{
			SDLVAL.typeDeclList = []*TypeDecl{SDLDollar[1].typeDecl}
		}
	case 45:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:402
		{
			SDLVAL.typeDeclList = append(SDLDollar[1].typeDeclList, SDLDollar[3].typeDecl)
		}
	case 46:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:406
		{ // USES($1) ...
			SDLVAL.usesDecl = &UsesDecl{
				NodeInfo:      NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].ident.End()),
				Name:          SDLDollar[2].ident,
				ComponentName: SDLDollar[3].ident,
			}
		}
	case 47:
		SDLDollar = SDLS[SDLpt-6 : SDLpt+1]
//line grammar.y:414
		{
			SDLVAL.usesDecl = &UsesDecl{
				NodeInfo:      NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[6].node.End()),
				Name:          SDLDollar[2].ident,
				ComponentName: SDLDollar[3].ident,
				Overrides:     SDLDollar[5].assignList,
			}
		}
	case 48:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:425
		{ // METHOD($1) ... BlockStmt($6)
			SDLDollar[2].methodDef.Body = SDLDollar[3].blockStmt
			SDLDollar[2].methodDef.NodeInfo.StopPos = SDLDollar[3].blockStmt.End()
			SDLVAL.methodDef = SDLDollar[2].methodDef
		}
	case 49:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:433
		{
			SDLVAL.paramList = []*ParamDecl{}
		}
	case 50:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:434
		{
			SDLVAL.paramList = SDLDollar[1].paramList
		}
	case 51:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:438
		{
			SDLVAL.paramList = []*ParamDecl{SDLDollar[1].paramDecl}
		}
	case 52:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:439
		{
			SDLVAL.paramList = append(SDLDollar[1].paramList, SDLDollar[3].paramDecl)
		}
	case 53:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:443
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[2].typeDecl.End()),
				Name:     SDLDollar[1].ident,
				TypeDecl: SDLDollar[2].typeDecl, // TypeDecl also needs to have NodeInfo
			}
		}
	case 54:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:450
		{ // PARAM($1) ...
			SDLVAL.paramDecl = &ParamDecl{
				NodeInfo:     NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[4].expr.End()),
				Name:         SDLDollar[1].ident,
				TypeDecl:     SDLDollar[2].typeDecl,
				DefaultValue: SDLDollar[4].expr,
			}
		}
	case 55:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:462
		{ // SYSTEM($1) ... RBRACE($5)
			SDLVAL.systemDecl = &SystemDecl{
				NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[5].node.(Node).End()),
				Name:     SDLDollar[2].ident,
				Body:     SDLDollar[4].sysBodyItemList,
			}
		}
	case 56:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:472
		{ // SYSTEM($1) ... RBRACE($5)
			SDLVAL.aggregatorDecl = &AggregatorDecl{
				NodeInfo:   NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].methodDef.End()),
				Name:       SDLDollar[3].methodDef.Name,
				Parameters: SDLDollar[3].methodDef.Parameters,
				ReturnType: SDLDollar[3].methodDef.ReturnType,
			}
		}
	case 57:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:483
		{
			SDLVAL.sysBodyItemList = []SystemDeclBodyItem{}
		}
	case 58:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:484
		{
			SDLVAL.sysBodyItemList = append(SDLDollar[1].sysBodyItemList, SDLDollar[2].node.(SystemDeclBodyItem))
		}
	case 59:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:488
		{
			SDLVAL.node = SDLDollar[1].instanceDecl
		}
	case 60:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:490
		{
			SDLVAL.node = SDLDollar[1].optionsDecl
		}
	case 61:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:491
		{
			SDLVAL.node = SDLDollar[1].stmt
		}
	case 62:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:495
		{ // IDENTIFIER($1) ...
			SDLVAL.instanceDecl = &InstanceDecl{
				NodeInfo:      NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].ident.End()),
				Name:          SDLDollar[2].ident,
				ComponentName: SDLDollar[3].ident,
				Overrides:     []*AssignmentStmt{},
			}
		}
	case 63:
		SDLDollar = SDLS[SDLpt-6 : SDLpt+1]
//line grammar.y:503
		{ // IDENTIFIER($1) ...
			SDLVAL.instanceDecl = &InstanceDecl{
				NodeInfo:      NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[6].node.End()),
				Name:          SDLDollar[2].ident,
				ComponentName: SDLDollar[3].ident,
				Overrides:     SDLDollar[5].assignList,
			}
		}
	case 64:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:514
		{
			SDLVAL.assignList = []*AssignmentStmt{}
		}
	case 65:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:515
		{
			SDLVAL.assignList = SDLDollar[1].assignList
		}
	case 66:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:519
		{
			SDLVAL.assignList = []*AssignmentStmt{SDLDollar[1].assignStmt}
		}
	case 67:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:520
		{
			SDLVAL.assignList = append(SDLDollar[1].assignList, SDLDollar[3].assignStmt)
		}
	case 68:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:524
		{ // IDENTIFIER($1) ...
			SDLVAL.assignStmt = &AssignmentStmt{
				NodeInfo: NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[3].expr.End()),
				Var:      SDLDollar[1].ident,
				Value:    SDLDollar[3].expr,
			}
		}
	case 69:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:535
		{
			SDLVAL.stmtList = []Stmt{}
		}
	case 70:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:536
		{
			SDLVAL.stmtList = SDLDollar[1].stmtList
			if SDLDollar[2].stmt != nil {
				SDLVAL.stmtList = append(SDLVAL.stmtList, SDLDollar[2].stmt)
			}
		}
	case 71:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:544
		{
			SDLVAL.stmt = SDLDollar[1].stmt
		}
	case 72:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:545
		{
			SDLVAL.stmt = SDLDollar[1].stmt
		}
	case 73:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:546
		{
			SDLVAL.stmt = SDLDollar[1].forStmt
		}
	case 74:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:547
		{
			SDLVAL.stmt = SDLDollar[1].stmt
		}
	case 75:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:548
		{
			SDLVAL.stmt = SDLDollar[1].ifStmt
		}
	case 76:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:549
		{
			SDLVAL.stmt = SDLDollar[1].delayStmt
		}
	case 77:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:550
		{
			SDLVAL.stmt = SDLDollar[1].switchStmt
		}
	case 78:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:551
		{
			SDLVAL.stmt = SDLDollar[1].blockStmt
		}
	case 79:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:552
		{
			SDLVAL.stmt = nil
		}
	case 80:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:557
		{
			SDLVAL.blockStmt = &BlockStmt{NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].node.(Node).End()), Statements: SDLDollar[2].stmtList}
		}
	case 81:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:562
		{
			SDLVAL.forStmt = &ForStmt{NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].stmt.End()), Condition: SDLDollar[2].expr, Body: SDLDollar[3].stmt}
		}
	case 82:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:568
		{ // LET($1) ...
			SDLVAL.stmt = &LetStmt{
				NodeInfo:  NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[4].expr.End()),
				Variables: SDLDollar[2].identList,
				Value:     SDLDollar[4].expr,
			}
		}
	case 83:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:593
		{
			SDLVAL.stmt = &ReturnStmt{NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.(Node).End()), ReturnValue: SDLDollar[2].expr}
		}
	case 84:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:594
		{
			SDLVAL.stmt = &ReturnStmt{NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].node.(Node).End()), ReturnValue: nil}
		}
	case 85:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:598
		{
			SDLVAL.delayStmt = &DelayStmt{NodeInfo: NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.End()), Duration: SDLDollar[2].expr}
		}
	case 86:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:602
		{ // WAIT($1) IDENTIFIER($2) ...
			idents := SDLDollar[2].identList
			endNode := idents[len(idents)-1] // End at the last identifier in the list
			SDLVAL.expr = &WaitExpr{FutureNames: idents}
			SDLVAL.expr.(*WaitExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.Pos(), endNode.End())
		}
	case 87:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:608
		{ // WAIT($1) IDENTIFIER($2) ...
			idents := SDLDollar[2].identList
			endNode := idents[len(idents)-1] // End at the last identifier in the list
			SDLVAL.expr = &WaitExpr{
				FutureNames:      idents,
				AggregatorName:   SDLDollar[4].expr.(*CallExpr).Function.(*IdentifierExpr),
				AggregatorParams: SDLDollar[4].expr.(*CallExpr).ArgMap,
			}
			SDLVAL.expr.(*WaitExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.Pos(), endNode.End())
		}
	case 88:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:635
		{
			SDLVAL.exprMap = map[string]Expr{SDLDollar[1].ident.Value: SDLDollar[3].expr}
		}
	case 89:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:636
		{
			name := SDLDollar[3].ident.Value
			SDLDollar[1].exprMap[name] = SDLDollar[5].expr
			SDLVAL.exprMap = SDLDollar[1].exprMap
		}
	case 90:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:644
		{
			SDLVAL.exprList = []Expr{SDLDollar[1].expr}
		}
	case 91:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:645
		{
			SDLVAL.exprList = append(SDLDollar[1].exprList, SDLDollar[3].expr)
		}
	case 92:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:650
		{ // IF($1) ...
			endNode := Stmt(SDLDollar[3].blockStmt)
			if SDLDollar[4].stmt != nil {
				endNode = SDLDollar[4].stmt
			} // End of Else block/IfStmt
			SDLVAL.ifStmt = &IfStmt{
				NodeInfo:  NewNodeInfo(SDLDollar[1].node.(Node).Pos(), endNode.End()),
				Condition: SDLDollar[2].expr,
				Then:      SDLDollar[3].blockStmt,
				Else:      SDLDollar[4].stmt,
			}
		}
	case 93:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:663
		{
			SDLVAL.stmt = nil
		}
	case 94:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:664
		{
			SDLVAL.stmt = SDLDollar[2].ifStmt
		}
	case 95:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:665
		{
			SDLVAL.stmt = SDLDollar[2].blockStmt
		}
	case 96:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:669
		{ // DISTRIBUTE($1) ... RBRACE($6)
			SDLVAL.sampleExpr = &SampleExpr{FromExpr: SDLDollar[2].expr}
			SDLVAL.sampleExpr.NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.(Node).End())
		}
	case 97:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:675
		{
			SDLVAL.expr = nil
		}
	case 98:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:675
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 99:
		SDLDollar = SDLS[SDLpt-5 : SDLpt+1]
//line grammar.y:677
		{
			SDLVAL.tupleExpr = &TupleExpr{Children: append(SDLDollar[2].exprList, SDLDollar[4].expr)}
		}
	case 100:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:682
		{ // GO($1) ... BlockStmt($4)
			SDLVAL.expr = &GoExpr{Stmt: SDLDollar[2].blockStmt}
			SDLVAL.expr.(*GoExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].blockStmt.End())
		}
	case 101:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:686
		{
			SDLVAL.expr = &GoExpr{Expr: SDLDollar[2].expr}
			SDLVAL.expr.(*GoExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.End())
		}
	case 102:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:690
		{ // GO($1) ... BlockStmt($4)
			SDLVAL.expr = &GoExpr{LoopExpr: SDLDollar[2].expr, Stmt: SDLDollar[3].blockStmt}
			SDLVAL.expr.(*GoExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].blockStmt.End())
		}
	case 103:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:694
		{
			SDLVAL.expr = &GoExpr{LoopExpr: SDLDollar[2].expr, Expr: SDLDollar[3].expr}
			SDLVAL.expr.(*GoExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[3].expr.End())
		}
	case 104:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:703
		{
			SDLDollar[1].chainedExpr.Unchain(nil)
			SDLVAL.expr = SDLDollar[1].chainedExpr.UnchainedExpr
		}
	case 105:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:707
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 106:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:708
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 107:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:735
		{
			SDLVAL.chainedExpr = &ChainedExpr{Children: []Expr{SDLDollar[1].expr}}
		}
	case 108:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:738
		{
			SDLDollar[1].chainedExpr.Children = append(SDLDollar[1].chainedExpr.Children, SDLDollar[3].expr)
			SDLDollar[1].chainedExpr.Operators = append(SDLDollar[1].chainedExpr.Operators, SDLDollar[2].node.String())
			SDLVAL.chainedExpr = SDLDollar[1].chainedExpr
		}
	case 109:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:743
		{
			SDLDollar[1].chainedExpr.Children = append(SDLDollar[1].chainedExpr.Children, SDLDollar[3].expr)
			SDLDollar[1].chainedExpr.Operators = append(SDLDollar[1].chainedExpr.Operators, SDLDollar[2].node.String())
			SDLVAL.chainedExpr = SDLDollar[1].chainedExpr
		}
	case 110:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:750
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 111:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:752
		{
			SDLVAL.expr = &UnaryExpr{Operator: SDLDollar[1].node.String(), Right: SDLDollar[2].expr}
			SDLVAL.expr.(*UnaryExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.(Node).End())
		}
	case 112:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:757
		{
			SDLVAL.expr = &UnaryExpr{Operator: SDLDollar[1].node.String(), Right: SDLDollar[2].expr}
			SDLVAL.expr.(*UnaryExpr).NodeInfo = NewNodeInfo(SDLDollar[1].node.(Node).Pos(), SDLDollar[2].expr.(Node).End())
		}
	case 113:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:765
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 114:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:766
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 115:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:770
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 116:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:771
		{
			SDLVAL.expr = SDLDollar[1].ident
		}
	case 117:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:772
		{
			SDLVAL.expr = SDLDollar[1].distributeExpr
		}
	case 118:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:773
		{
			SDLVAL.expr = SDLDollar[1].sampleExpr
		}
	case 119:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:774
		{
			SDLVAL.expr = SDLDollar[1].tupleExpr
		}
	case 120:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:775
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 121:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:776
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 122:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:777
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 123:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:780
		{
			SDLVAL.expr = SDLDollar[2].expr
		}
	case 124:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:783
		{
			// SDLlex.(*Lexer).lval)
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 125:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:787
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 126:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:788
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 127:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:789
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 128:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:790
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 129:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:794
		{ // Expression "[" Key "]"
			SDLVAL.expr = &IndexExpr{
				Receiver: SDLDollar[1].expr,
				Key:      SDLDollar[3].expr,
			}
			SDLVAL.expr.(*IndexExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), SDLDollar[4].node.End())
		}
	case 130:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:804
		{ // PrimaryExpr($1) DOT($2) IDENTIFIER($3)
			SDLVAL.expr = &MemberAccessExpr{
				Receiver: SDLDollar[1].ident,
				Member:   SDLDollar[3].ident,
			}
			SDLVAL.expr.(*MemberAccessExpr).NodeInfo = NewNodeInfo(SDLDollar[1].ident.Pos(), SDLDollar[3].ident.End())
		}
	case 131:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:811
		{ // PrimaryExpr($1) DOT($2) IDENTIFIER($3)
			SDLVAL.expr = &MemberAccessExpr{
				Receiver: SDLDollar[1].expr,
				Member:   SDLDollar[3].ident,
			}
			SDLVAL.expr.(*MemberAccessExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), SDLDollar[3].ident.End())
		}
	case 132:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:821
		{ // PrimaryExpr($1) LPAREN($2) ArgList($3) RPAREN($4)
			SDLVAL.expr = &CallExpr{Function: SDLDollar[1].expr}
			SDLVAL.expr.(*CallExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), SDLDollar[3].node.End())
		}
	case 133:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:825
		{ // PrimaryExpr($1) LPAREN($2) ArgList($3) RPAREN($4)
			endNode := SDLDollar[4].node.(Node) // End at RPAREN
			if len(SDLDollar[3].exprList) > 0 {
				exprList := SDLDollar[3].exprList
				endNode = exprList[len(exprList)-1].(Node) // End at last arg
			}
			SDLVAL.expr = &CallExpr{
				Function: SDLDollar[1].expr,
				ArgList:  SDLDollar[3].exprList,
			}
			SDLVAL.expr.(*CallExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), endNode.End())
		}
	case 134:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:837
		{ // PrimaryExpr($1) LPAREN($2) ArgList($3) RPAREN($4)
			endNode := SDLDollar[4].node.(Node) // End at RPAREN
			SDLVAL.expr = &CallExpr{
				Function: SDLDollar[1].expr,
				IsNamed:  true,
				ArgMap:   SDLDollar[3].exprMap,
			}
			SDLVAL.expr.(*CallExpr).NodeInfo = NewNodeInfo(SDLDollar[1].expr.Pos(), endNode.End())
		}
	case 135:
		SDLDollar = SDLS[SDLpt-6 : SDLpt+1]
//line grammar.y:849
		{
			SDLVAL.distributeExpr = &DistributeExpr{TotalProb: SDLDollar[2].expr, Cases: SDLDollar[4].caseExprList, Default: SDLDollar[5].expr} /* TODO: Pos */
		}
	case 136:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:855
		{
			SDLVAL.caseExprList = []*CaseExpr{}
		}
	case 137:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:856
		{
			SDLVAL.caseExprList = SDLDollar[1].caseExprList
		}
	case 138:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:860
		{
			SDLVAL.caseExprList = []*CaseExpr{SDLDollar[1].caseExpr}
		}
	case 139:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:861
		{
			SDLVAL.caseExprList = append(SDLDollar[1].caseExprList, SDLDollar[2].caseExpr)
		}
	case 140:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:865
		{
			SDLVAL.caseExpr = &CaseExpr{Condition: SDLDollar[1].expr, Body: SDLDollar[3].expr}
		}
	case 141:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:868
		{ // allow optional comma
			SDLVAL.caseExpr = &CaseExpr{Condition: SDLDollar[1].expr, Body: SDLDollar[3].expr}
		}
	case 142:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:874
		{
			SDLVAL.expr = nil
		}
	case 143:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:875
		{
			SDLVAL.expr = SDLDollar[1].expr
		}
	case 144:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:879
		{
			SDLVAL.expr = SDLDollar[3].expr
		}
	case 145:
		SDLDollar = SDLS[SDLpt-4 : SDLpt+1]
//line grammar.y:880
		{
			SDLVAL.expr = SDLDollar[3].expr
		}
	case 146:
		SDLDollar = SDLS[SDLpt-6 : SDLpt+1]
//line grammar.y:884
		{
			SDLVAL.switchStmt = &SwitchStmt{Expr: SDLDollar[2].expr, Cases: SDLDollar[4].caseStmtList, Default: SDLDollar[5].stmt} /* TODO: Pos */
		}
	case 147:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:890
		{
			SDLVAL.caseStmtList = []*CaseStmt{}
		}
	case 148:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:891
		{
			SDLVAL.caseStmtList = SDLDollar[1].caseStmtList
		}
	case 149:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:895
		{
			SDLVAL.caseStmtList = []*CaseStmt{SDLDollar[1].caseStmt}
		}
	case 150:
		SDLDollar = SDLS[SDLpt-2 : SDLpt+1]
//line grammar.y:896
		{
			SDLVAL.caseStmtList = append(SDLDollar[1].caseStmtList, SDLDollar[2].caseStmt)
		}
	case 151:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:900
		{
			SDLVAL.caseStmt = &CaseStmt{NodeInfo: NewNodeInfo(SDLDollar[1].expr.(Node).Pos(), SDLDollar[3].stmt.End()), Condition: SDLDollar[1].expr, Body: SDLDollar[3].stmt}
		}
	case 152:
		SDLDollar = SDLS[SDLpt-0 : SDLpt+1]
//line grammar.y:904
		{
			SDLVAL.stmt = nil
		}
	case 153:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:905
		{
			SDLVAL.stmt = SDLDollar[1].stmt
		}
	case 154:
		SDLDollar = SDLS[SDLpt-3 : SDLpt+1]
//line grammar.y:909
		{
			SDLVAL.stmt = SDLDollar[3].stmt
		}
	case 155:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:913
		{
			SDLVAL.stmt = &ExprStmt{NodeInfo: NewNodeInfo(SDLDollar[1].expr.(Node).Pos(), SDLDollar[1].expr.(Node).End()), Expression: SDLDollar[1].expr}
		}
	case 156:
		SDLDollar = SDLS[SDLpt-1 : SDLpt+1]
//line grammar.y:914
		{
			SDLVAL.stmt = &ExprStmt{NodeInfo: NewNodeInfo(SDLDollar[1].expr.(Node).Pos(), SDLDollar[1].expr.(Node).End()), Expression: SDLDollar[1].expr}
		}
	}
	goto SDLstack /* stack new state and value */
}
