/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1SectionType } from './V1SectionType';
import {
    V1SectionTypeFromJSON,
    V1SectionTypeFromJSONTyped,
    V1SectionTypeToJSON,
    V1SectionTypeToJSONTyped,
} from './V1SectionType';

/**
 * 
 * @export
 * @interface DesignServiceAddSectionRequestSection
 */
export interface DesignServiceAddSectionRequestSection {
    /**
     * 
     * @type {Date}
     * @memberof DesignServiceAddSectionRequestSection
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DesignServiceAddSectionRequestSection
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof DesignServiceAddSectionRequestSection
     */
    id?: string;
    /**
     * 
     * @type {V1SectionType}
     * @memberof DesignServiceAddSectionRequestSection
     */
    type?: V1SectionType;
    /**
     * *
     * Title of this section.
     * @type {string}
     * @memberof DesignServiceAddSectionRequestSection
     */
    title?: string;
    /**
     * *
     * A description of the section to help make sense of why this is here.
     * @type {string}
     * @memberof DesignServiceAddSectionRequestSection
     */
    description?: string;
    /**
     * *
     * Order of the section in the list of sections.  This is a readonly field.
     * @type {number}
     * @memberof DesignServiceAddSectionRequestSection
     */
    order?: number;
}



/**
 * Check if a given object implements the DesignServiceAddSectionRequestSection interface.
 */
export function instanceOfDesignServiceAddSectionRequestSection(value: object): value is DesignServiceAddSectionRequestSection {
    return true;
}

export function DesignServiceAddSectionRequestSectionFromJSON(json: any): DesignServiceAddSectionRequestSection {
    return DesignServiceAddSectionRequestSectionFromJSONTyped(json, false);
}

export function DesignServiceAddSectionRequestSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DesignServiceAddSectionRequestSection {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : V1SectionTypeFromJSON(json['type']),
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function DesignServiceAddSectionRequestSectionToJSON(json: any): DesignServiceAddSectionRequestSection {
    return DesignServiceAddSectionRequestSectionToJSONTyped(json, false);
}

export function DesignServiceAddSectionRequestSectionToJSONTyped(value?: DesignServiceAddSectionRequestSection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'id': value['id'],
        'type': V1SectionTypeToJSON(value['type']),
        'title': value['title'],
        'description': value['description'],
        'order': value['order'],
    };
}

