/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PositionType } from './V1PositionType';
import {
    V1PositionTypeFromJSON,
    V1PositionTypeFromJSONTyped,
    V1PositionTypeToJSON,
    V1PositionTypeToJSONTyped,
} from './V1PositionType';

/**
 * 
 * @export
 * @interface DesignServiceMoveSectionRequest
 */
export interface DesignServiceMoveSectionRequest {
    /**
     * 
     * @type {string}
     * @memberof DesignServiceMoveSectionRequest
     */
    relativeSectionId?: string;
    /**
     * 
     * @type {V1PositionType}
     * @memberof DesignServiceMoveSectionRequest
     */
    position?: V1PositionType;
}



/**
 * Check if a given object implements the DesignServiceMoveSectionRequest interface.
 */
export function instanceOfDesignServiceMoveSectionRequest(value: object): value is DesignServiceMoveSectionRequest {
    return true;
}

export function DesignServiceMoveSectionRequestFromJSON(json: any): DesignServiceMoveSectionRequest {
    return DesignServiceMoveSectionRequestFromJSONTyped(json, false);
}

export function DesignServiceMoveSectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DesignServiceMoveSectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'relativeSectionId': json['relativeSectionId'] == null ? undefined : json['relativeSectionId'],
        'position': json['position'] == null ? undefined : V1PositionTypeFromJSON(json['position']),
    };
}

export function DesignServiceMoveSectionRequestToJSON(json: any): DesignServiceMoveSectionRequest {
    return DesignServiceMoveSectionRequestToJSONTyped(json, false);
}

export function DesignServiceMoveSectionRequestToJSONTyped(value?: DesignServiceMoveSectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relativeSectionId': value['relativeSectionId'],
        'position': V1PositionTypeToJSON(value['position']),
    };
}

