/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PositionType } from './V1PositionType';
import {
    V1PositionTypeFromJSON,
    V1PositionTypeFromJSONTyped,
    V1PositionTypeToJSON,
    V1PositionTypeToJSONTyped,
} from './V1PositionType';
import type { DesignServiceAddSectionRequestSection } from './DesignServiceAddSectionRequestSection';
import {
    DesignServiceAddSectionRequestSectionFromJSON,
    DesignServiceAddSectionRequestSectionFromJSONTyped,
    DesignServiceAddSectionRequestSectionToJSON,
    DesignServiceAddSectionRequestSectionToJSONTyped,
} from './DesignServiceAddSectionRequestSection';

/**
 * 
 * @export
 * @interface DesignServiceAddSectionRequest
 */
export interface DesignServiceAddSectionRequest {
    /**
     * 
     * @type {DesignServiceAddSectionRequestSection}
     * @memberof DesignServiceAddSectionRequest
     */
    section?: DesignServiceAddSectionRequestSection;
    /**
     * 
     * @type {string}
     * @memberof DesignServiceAddSectionRequest
     */
    relativeSectionId?: string;
    /**
     * 
     * @type {V1PositionType}
     * @memberof DesignServiceAddSectionRequest
     */
    position?: V1PositionType;
    /**
     * 
     * @type {string}
     * @memberof DesignServiceAddSectionRequest
     */
    initialGetAnswerPrompt?: string;
    /**
     * 
     * @type {string}
     * @memberof DesignServiceAddSectionRequest
     */
    initialVerifyPrompt?: string;
}



/**
 * Check if a given object implements the DesignServiceAddSectionRequest interface.
 */
export function instanceOfDesignServiceAddSectionRequest(value: object): value is DesignServiceAddSectionRequest {
    return true;
}

export function DesignServiceAddSectionRequestFromJSON(json: any): DesignServiceAddSectionRequest {
    return DesignServiceAddSectionRequestFromJSONTyped(json, false);
}

export function DesignServiceAddSectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DesignServiceAddSectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'section': json['section'] == null ? undefined : DesignServiceAddSectionRequestSectionFromJSON(json['section']),
        'relativeSectionId': json['relativeSectionId'] == null ? undefined : json['relativeSectionId'],
        'position': json['position'] == null ? undefined : V1PositionTypeFromJSON(json['position']),
        'initialGetAnswerPrompt': json['initialGetAnswerPrompt'] == null ? undefined : json['initialGetAnswerPrompt'],
        'initialVerifyPrompt': json['initialVerifyPrompt'] == null ? undefined : json['initialVerifyPrompt'],
    };
}

export function DesignServiceAddSectionRequestToJSON(json: any): DesignServiceAddSectionRequest {
    return DesignServiceAddSectionRequestToJSONTyped(json, false);
}

export function DesignServiceAddSectionRequestToJSONTyped(value?: DesignServiceAddSectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'section': DesignServiceAddSectionRequestSectionToJSON(value['section']),
        'relativeSectionId': value['relativeSectionId'],
        'position': V1PositionTypeToJSON(value['position']),
        'initialGetAnswerPrompt': value['initialGetAnswerPrompt'],
        'initialVerifyPrompt': value['initialVerifyPrompt'],
    };
}

