/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LlmServiceGenerateTextContentRequest
 */
export interface LlmServiceGenerateTextContentRequest {
    /**
     * Optional: Provide a specific prompt or template identifier.
     * If empty, the service might use a default based on the section title.
     * 
     * Optional: Flags for generation options (e.g., include best practices)
     *  map<string, bool> options = 4;
     * @type {string}
     * @memberof LlmServiceGenerateTextContentRequest
     */
    promptOverride?: string;
}

/**
 * Check if a given object implements the LlmServiceGenerateTextContentRequest interface.
 */
export function instanceOfLlmServiceGenerateTextContentRequest(value: object): value is LlmServiceGenerateTextContentRequest {
    return true;
}

export function LlmServiceGenerateTextContentRequestFromJSON(json: any): LlmServiceGenerateTextContentRequest {
    return LlmServiceGenerateTextContentRequestFromJSONTyped(json, false);
}

export function LlmServiceGenerateTextContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmServiceGenerateTextContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'promptOverride': json['promptOverride'] == null ? undefined : json['promptOverride'],
    };
}

export function LlmServiceGenerateTextContentRequestToJSON(json: any): LlmServiceGenerateTextContentRequest {
    return LlmServiceGenerateTextContentRequestToJSONTyped(json, false);
}

export function LlmServiceGenerateTextContentRequestToJSONTyped(value?: LlmServiceGenerateTextContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promptOverride': value['promptOverride'],
    };
}

