/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LlmServiceSuggestSectionsRequest
 */
export interface LlmServiceSuggestSectionsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof LlmServiceSuggestSectionsRequest
     */
    existingSectionTitles?: Array<string>;
}

/**
 * Check if a given object implements the LlmServiceSuggestSectionsRequest interface.
 */
export function instanceOfLlmServiceSuggestSectionsRequest(value: object): value is LlmServiceSuggestSectionsRequest {
    return true;
}

export function LlmServiceSuggestSectionsRequestFromJSON(json: any): LlmServiceSuggestSectionsRequest {
    return LlmServiceSuggestSectionsRequestFromJSONTyped(json, false);
}

export function LlmServiceSuggestSectionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmServiceSuggestSectionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'existingSectionTitles': json['existingSectionTitles'] == null ? undefined : json['existingSectionTitles'],
    };
}

export function LlmServiceSuggestSectionsRequestToJSON(json: any): LlmServiceSuggestSectionsRequest {
    return LlmServiceSuggestSectionsRequestToJSONTyped(json, false);
}

export function LlmServiceSuggestSectionsRequestToJSONTyped(value?: LlmServiceSuggestSectionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'existingSectionTitles': value['existingSectionTitles'],
    };
}

