/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DesignBeingUpdated } from './DesignBeingUpdated';
import {
    DesignBeingUpdatedFromJSON,
    DesignBeingUpdatedFromJSONTyped,
    DesignBeingUpdatedToJSON,
    DesignBeingUpdatedToJSONTyped,
} from './DesignBeingUpdated';

/**
 * *
 * The request for (partially) updating an Design.  Note this only updates design level metadata.
 * Specific changes to section contetn will not happen here.
 * @export
 * @interface UpdateDesignRequest
 */
export interface UpdateDesignRequest {
    /**
     * 
     * @type {DesignBeingUpdated}
     * @memberof UpdateDesignRequest
     */
    design?: DesignBeingUpdated;
    /**
     * *
     * Mask of fields being updated in this Design to make partial changes.
     * @type {string}
     * @memberof UpdateDesignRequest
     */
    updateMask?: string;
}

/**
 * Check if a given object implements the UpdateDesignRequest interface.
 */
export function instanceOfUpdateDesignRequest(value: object): value is UpdateDesignRequest {
    return true;
}

export function UpdateDesignRequestFromJSON(json: any): UpdateDesignRequest {
    return UpdateDesignRequestFromJSONTyped(json, false);
}

export function UpdateDesignRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDesignRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'design': json['design'] == null ? undefined : DesignBeingUpdatedFromJSON(json['design']),
        'updateMask': json['updateMask'] == null ? undefined : json['updateMask'],
    };
}

export function UpdateDesignRequestToJSON(json: any): UpdateDesignRequest {
    return UpdateDesignRequestToJSONTyped(json, false);
}

export function UpdateDesignRequestToJSONTyped(value?: UpdateDesignRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'design': DesignBeingUpdatedToJSON(value['design']),
        'updateMask': value['updateMask'],
    };
}

