/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagBeingUpdated } from './TagBeingUpdated';
import {
    TagBeingUpdatedFromJSON,
    TagBeingUpdatedFromJSONTyped,
    TagBeingUpdatedToJSON,
    TagBeingUpdatedToJSONTyped,
} from './TagBeingUpdated';

/**
 * *
 * The request for (partially) updating an Tag.
 * @export
 * @interface UpdateTagRequest
 */
export interface UpdateTagRequest {
    /**
     * 
     * @type {TagBeingUpdated}
     * @memberof UpdateTagRequest
     */
    tag?: TagBeingUpdated;
    /**
     * *
     * Mask of fields being updated in this Tag to make partial changes.
     * @type {string}
     * @memberof UpdateTagRequest
     */
    updateMask?: string;
}

/**
 * Check if a given object implements the UpdateTagRequest interface.
 */
export function instanceOfUpdateTagRequest(value: object): value is UpdateTagRequest {
    return true;
}

export function UpdateTagRequestFromJSON(json: any): UpdateTagRequest {
    return UpdateTagRequestFromJSONTyped(json, false);
}

export function UpdateTagRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTagRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : TagBeingUpdatedFromJSON(json['tag']),
        'updateMask': json['updateMask'] == null ? undefined : json['updateMask'],
    };
}

export function UpdateTagRequestToJSON(json: any): UpdateTagRequest {
    return UpdateTagRequestToJSONTyped(json, false);
}

export function UpdateTagRequestToJSONTyped(value?: UpdateTagRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': TagBeingUpdatedToJSON(value['tag']),
        'updateMask': value['updateMask'],
    };
}

