/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Leetcoachv1Tag } from './Leetcoachv1Tag';
import {
    Leetcoachv1TagFromJSON,
    Leetcoachv1TagFromJSONTyped,
    Leetcoachv1TagToJSON,
    Leetcoachv1TagToJSONTyped,
} from './Leetcoachv1Tag';

/**
 * *
 * Response of an tag creation.
 * @export
 * @interface V1CreateTagResponse
 */
export interface V1CreateTagResponse {
    /**
     * 
     * @type {Leetcoachv1Tag}
     * @memberof V1CreateTagResponse
     */
    tag?: Leetcoachv1Tag;
    /**
     * *
     * Error specific to a field if there are any errors.
     * @type {{ [key: string]: string; }}
     * @memberof V1CreateTagResponse
     */
    fieldErrors?: { [key: string]: string; };
}

/**
 * Check if a given object implements the V1CreateTagResponse interface.
 */
export function instanceOfV1CreateTagResponse(value: object): value is V1CreateTagResponse {
    return true;
}

export function V1CreateTagResponseFromJSON(json: any): V1CreateTagResponse {
    return V1CreateTagResponseFromJSONTyped(json, false);
}

export function V1CreateTagResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateTagResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : Leetcoachv1TagFromJSON(json['tag']),
        'fieldErrors': json['fieldErrors'] == null ? undefined : json['fieldErrors'],
    };
}

export function V1CreateTagResponseToJSON(json: any): V1CreateTagResponse {
    return V1CreateTagResponseToJSONTyped(json, false);
}

export function V1CreateTagResponseToJSONTyped(value?: V1CreateTagResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': Leetcoachv1TagToJSON(value['tag']),
        'fieldErrors': value['fieldErrors'],
    };
}

