/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Design } from './V1Design';
import {
    V1DesignFromJSON,
    V1DesignFromJSONTyped,
    V1DesignToJSON,
    V1DesignToJSONTyped,
} from './V1Design';

/**
 * *
 * Response of an design creation.
 * @export
 * @interface V1CreateDesignResponse
 */
export interface V1CreateDesignResponse {
    /**
     * 
     * @type {V1Design}
     * @memberof V1CreateDesignResponse
     */
    design?: V1Design;
    /**
     * *
     * Error specific to a field if there are any errors.
     * @type {{ [key: string]: string; }}
     * @memberof V1CreateDesignResponse
     */
    fieldErrors?: { [key: string]: string; };
}

/**
 * Check if a given object implements the V1CreateDesignResponse interface.
 */
export function instanceOfV1CreateDesignResponse(value: object): value is V1CreateDesignResponse {
    return true;
}

export function V1CreateDesignResponseFromJSON(json: any): V1CreateDesignResponse {
    return V1CreateDesignResponseFromJSONTyped(json, false);
}

export function V1CreateDesignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateDesignResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'design': json['design'] == null ? undefined : V1DesignFromJSON(json['design']),
        'fieldErrors': json['fieldErrors'] == null ? undefined : json['fieldErrors'],
    };
}

export function V1CreateDesignResponseToJSON(json: any): V1CreateDesignResponse {
    return V1CreateDesignResponseToJSONTyped(json, false);
}

export function V1CreateDesignResponseToJSONTyped(value?: V1CreateDesignResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'design': V1DesignToJSON(value['design']),
        'fieldErrors': value['fieldErrors'],
    };
}

