/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Design } from './V1Design';
import {
    V1DesignFromJSON,
    V1DesignFromJSONTyped,
    V1DesignToJSON,
    V1DesignToJSONTyped,
} from './V1Design';

/**
 * 
 * @export
 * @interface V1CreateDesignRequest
 */
export interface V1CreateDesignRequest {
    /**
     * 
     * @type {V1Design}
     * @memberof V1CreateDesignRequest
     */
    design?: V1Design;
}

/**
 * Check if a given object implements the V1CreateDesignRequest interface.
 */
export function instanceOfV1CreateDesignRequest(value: object): value is V1CreateDesignRequest {
    return true;
}

export function V1CreateDesignRequestFromJSON(json: any): V1CreateDesignRequest {
    return V1CreateDesignRequestFromJSONTyped(json, false);
}

export function V1CreateDesignRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateDesignRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'design': json['design'] == null ? undefined : V1DesignFromJSON(json['design']),
    };
}

export function V1CreateDesignRequestToJSON(json: any): V1CreateDesignRequest {
    return V1CreateDesignRequestToJSONTyped(json, false);
}

export function V1CreateDesignRequestToJSONTyped(value?: V1CreateDesignRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'design': V1DesignToJSON(value['design']),
    };
}

