/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Design } from './V1Design';
import {
    V1DesignFromJSON,
    V1DesignFromJSONTyped,
    V1DesignToJSON,
    V1DesignToJSONTyped,
} from './V1Design';

/**
 * 
 * @export
 * @interface V1GetDesignsResponse
 */
export interface V1GetDesignsResponse {
    /**
     * 
     * @type {{ [key: string]: V1Design; }}
     * @memberof V1GetDesignsResponse
     */
    designs?: { [key: string]: V1Design; };
}

/**
 * Check if a given object implements the V1GetDesignsResponse interface.
 */
export function instanceOfV1GetDesignsResponse(value: object): value is V1GetDesignsResponse {
    return true;
}

export function V1GetDesignsResponseFromJSON(json: any): V1GetDesignsResponse {
    return V1GetDesignsResponseFromJSONTyped(json, false);
}

export function V1GetDesignsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetDesignsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'designs': json['designs'] == null ? undefined : (mapValues(json['designs'], V1DesignFromJSON)),
    };
}

export function V1GetDesignsResponseToJSON(json: any): V1GetDesignsResponse {
    return V1GetDesignsResponseToJSONTyped(json, false);
}

export function V1GetDesignsResponseToJSONTyped(value?: V1GetDesignsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'designs': value['designs'] == null ? undefined : (mapValues(value['designs'], V1DesignToJSON)),
    };
}

