/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Leetcoachv1Tag } from './Leetcoachv1Tag';
import {
    Leetcoachv1TagFromJSON,
    Leetcoachv1TagFromJSONTyped,
    Leetcoachv1TagToJSON,
    Leetcoachv1TagToJSONTyped,
} from './Leetcoachv1Tag';

/**
 * 
 * @export
 * @interface V1GetTagsResponse
 */
export interface V1GetTagsResponse {
    /**
     * 
     * @type {{ [key: string]: Leetcoachv1Tag; }}
     * @memberof V1GetTagsResponse
     */
    tags?: { [key: string]: Leetcoachv1Tag; };
}

/**
 * Check if a given object implements the V1GetTagsResponse interface.
 */
export function instanceOfV1GetTagsResponse(value: object): value is V1GetTagsResponse {
    return true;
}

export function V1GetTagsResponseFromJSON(json: any): V1GetTagsResponse {
    return V1GetTagsResponseFromJSONTyped(json, false);
}

export function V1GetTagsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetTagsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : (mapValues(json['tags'], Leetcoachv1TagFromJSON)),
    };
}

export function V1GetTagsResponseToJSON(json: any): V1GetTagsResponse {
    return V1GetTagsResponseToJSONTyped(json, false);
}

export function V1GetTagsResponseToJSONTyped(value?: V1GetTagsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'] == null ? undefined : (mapValues(value['tags'], Leetcoachv1TagToJSON)),
    };
}

