/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Leetcoachv1Tag } from './Leetcoachv1Tag';
import {
    Leetcoachv1TagFromJSON,
    Leetcoachv1TagFromJSONTyped,
    Leetcoachv1TagToJSON,
    Leetcoachv1TagToJSONTyped,
} from './Leetcoachv1Tag';

/**
 * 
 * @export
 * @interface V1GetTagResponse
 */
export interface V1GetTagResponse {
    /**
     * 
     * @type {Leetcoachv1Tag}
     * @memberof V1GetTagResponse
     */
    tag?: Leetcoachv1Tag;
}

/**
 * Check if a given object implements the V1GetTagResponse interface.
 */
export function instanceOfV1GetTagResponse(value: object): value is V1GetTagResponse {
    return true;
}

export function V1GetTagResponseFromJSON(json: any): V1GetTagResponse {
    return V1GetTagResponseFromJSONTyped(json, false);
}

export function V1GetTagResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetTagResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : Leetcoachv1TagFromJSON(json['tag']),
    };
}

export function V1GetTagResponseToJSON(json: any): V1GetTagResponse {
    return V1GetTagResponseToJSONTyped(json, false);
}

export function V1GetTagResponseToJSONTyped(value?: V1GetTagResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': Leetcoachv1TagToJSON(value['tag']),
    };
}

