/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GenerateDefaultPromptsResponse
 */
export interface V1GenerateDefaultPromptsResponse {
    /**
     * The default prompt generated and saved for getting answers.
     * @type {string}
     * @memberof V1GenerateDefaultPromptsResponse
     */
    getAnswerPrompt?: string;
    /**
     * The default prompt generated and saved for verification.
     * @type {string}
     * @memberof V1GenerateDefaultPromptsResponse
     */
    verifyAnswerPrompt?: string;
}

/**
 * Check if a given object implements the V1GenerateDefaultPromptsResponse interface.
 */
export function instanceOfV1GenerateDefaultPromptsResponse(value: object): value is V1GenerateDefaultPromptsResponse {
    return true;
}

export function V1GenerateDefaultPromptsResponseFromJSON(json: any): V1GenerateDefaultPromptsResponse {
    return V1GenerateDefaultPromptsResponseFromJSONTyped(json, false);
}

export function V1GenerateDefaultPromptsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GenerateDefaultPromptsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'getAnswerPrompt': json['getAnswerPrompt'] == null ? undefined : json['getAnswerPrompt'],
        'verifyAnswerPrompt': json['verifyAnswerPrompt'] == null ? undefined : json['verifyAnswerPrompt'],
    };
}

export function V1GenerateDefaultPromptsResponseToJSON(json: any): V1GenerateDefaultPromptsResponse {
    return V1GenerateDefaultPromptsResponseToJSONTyped(json, false);
}

export function V1GenerateDefaultPromptsResponseToJSONTyped(value?: V1GenerateDefaultPromptsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'getAnswerPrompt': value['getAnswerPrompt'],
        'verifyAnswerPrompt': value['verifyAnswerPrompt'],
    };
}

