/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GenerateTextContentResponse
 */
export interface V1GenerateTextContentResponse {
    /**
     * 
     * @type {string}
     * @memberof V1GenerateTextContentResponse
     */
    generatedText?: string;
}

/**
 * Check if a given object implements the V1GenerateTextContentResponse interface.
 */
export function instanceOfV1GenerateTextContentResponse(value: object): value is V1GenerateTextContentResponse {
    return true;
}

export function V1GenerateTextContentResponseFromJSON(json: any): V1GenerateTextContentResponse {
    return V1GenerateTextContentResponseFromJSONTyped(json, false);
}

export function V1GenerateTextContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GenerateTextContentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedText': json['generatedText'] == null ? undefined : json['generatedText'],
    };
}

export function V1GenerateTextContentResponseToJSON(json: any): V1GenerateTextContentResponse {
    return V1GenerateTextContentResponseToJSONTyped(json, false);
}

export function V1GenerateTextContentResponseToJSONTyped(value?: V1GenerateTextContentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generatedText': value['generatedText'],
    };
}

