/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Section } from './V1Section';
import {
    V1SectionFromJSON,
    V1SectionFromJSONTyped,
    V1SectionToJSON,
    V1SectionToJSONTyped,
} from './V1Section';
import type { V1Design } from './V1Design';
import {
    V1DesignFromJSON,
    V1DesignFromJSONTyped,
    V1DesignToJSON,
    V1DesignToJSONTyped,
} from './V1Design';

/**
 * 
 * @export
 * @interface V1GetDesignResponse
 */
export interface V1GetDesignResponse {
    /**
     * 
     * @type {V1Design}
     * @memberof V1GetDesignResponse
     */
    design?: V1Design;
    /**
     * Optionally populated by server if include_section_metadata was true.
     * Sections in this list will *not* have their 'content' oneof populated.
     * The order should match design.section_ids.
     * @type {Array<V1Section>}
     * @memberof V1GetDesignResponse
     */
    sectionsMetadata?: Array<V1Section>;
}

/**
 * Check if a given object implements the V1GetDesignResponse interface.
 */
export function instanceOfV1GetDesignResponse(value: object): value is V1GetDesignResponse {
    return true;
}

export function V1GetDesignResponseFromJSON(json: any): V1GetDesignResponse {
    return V1GetDesignResponseFromJSONTyped(json, false);
}

export function V1GetDesignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetDesignResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'design': json['design'] == null ? undefined : V1DesignFromJSON(json['design']),
        'sectionsMetadata': json['sectionsMetadata'] == null ? undefined : ((json['sectionsMetadata'] as Array<any>).map(V1SectionFromJSON)),
    };
}

export function V1GetDesignResponseToJSON(json: any): V1GetDesignResponse {
    return V1GetDesignResponseToJSONTyped(json, false);
}

export function V1GetDesignResponseToJSONTyped(value?: V1GetDesignResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'design': V1DesignToJSON(value['design']),
        'sectionsMetadata': value['sectionsMetadata'] == null ? undefined : ((value['sectionsMetadata'] as Array<any>).map(V1SectionToJSON)),
    };
}

