/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PaginationResponse } from './V1PaginationResponse';
import {
    V1PaginationResponseFromJSON,
    V1PaginationResponseFromJSONTyped,
    V1PaginationResponseToJSON,
    V1PaginationResponseToJSONTyped,
} from './V1PaginationResponse';
import type { V1Design } from './V1Design';
import {
    V1DesignFromJSON,
    V1DesignFromJSONTyped,
    V1DesignToJSON,
    V1DesignToJSONTyped,
} from './V1Design';

/**
 * *
 * Response of a design search/listing.
 * @export
 * @interface V1ListDesignsResponse
 */
export interface V1ListDesignsResponse {
    /**
     * *
     * The list of designs found as part of this response.
     * @type {Array<V1Design>}
     * @memberof V1ListDesignsResponse
     */
    designs?: Array<V1Design>;
    /**
     * 
     * @type {V1PaginationResponse}
     * @memberof V1ListDesignsResponse
     */
    pagination?: V1PaginationResponse;
}

/**
 * Check if a given object implements the V1ListDesignsResponse interface.
 */
export function instanceOfV1ListDesignsResponse(value: object): value is V1ListDesignsResponse {
    return true;
}

export function V1ListDesignsResponseFromJSON(json: any): V1ListDesignsResponse {
    return V1ListDesignsResponseFromJSONTyped(json, false);
}

export function V1ListDesignsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListDesignsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'designs': json['designs'] == null ? undefined : ((json['designs'] as Array<any>).map(V1DesignFromJSON)),
        'pagination': json['pagination'] == null ? undefined : V1PaginationResponseFromJSON(json['pagination']),
    };
}

export function V1ListDesignsResponseToJSON(json: any): V1ListDesignsResponse {
    return V1ListDesignsResponseToJSONTyped(json, false);
}

export function V1ListDesignsResponseToJSONTyped(value?: V1ListDesignsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'designs': value['designs'] == null ? undefined : ((value['designs'] as Array<any>).map(V1DesignToJSON)),
        'pagination': V1PaginationResponseToJSON(value['pagination']),
    };
}

