/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Leetcoachv1Tag } from './Leetcoachv1Tag';
import {
    Leetcoachv1TagFromJSON,
    Leetcoachv1TagFromJSONTyped,
    Leetcoachv1TagToJSON,
    Leetcoachv1TagToJSONTyped,
} from './Leetcoachv1Tag';

/**
 * *
 * Response of a tag search/listing.
 * @export
 * @interface V1ListTagsResponse
 */
export interface V1ListTagsResponse {
    /**
     * *
     * The list of tags found as part of this response.
     * @type {Array<Leetcoachv1Tag>}
     * @memberof V1ListTagsResponse
     */
    tags?: Array<Leetcoachv1Tag>;
    /**
     * *
     * The key/pointer string that subsequent List requests should pass to
     * continue the pagination.
     * @type {string}
     * @memberof V1ListTagsResponse
     */
    nextPageKey?: string;
}

/**
 * Check if a given object implements the V1ListTagsResponse interface.
 */
export function instanceOfV1ListTagsResponse(value: object): value is V1ListTagsResponse {
    return true;
}

export function V1ListTagsResponseFromJSON(json: any): V1ListTagsResponse {
    return V1ListTagsResponseFromJSONTyped(json, false);
}

export function V1ListTagsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListTagsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(Leetcoachv1TagFromJSON)),
        'nextPageKey': json['nextPageKey'] == null ? undefined : json['nextPageKey'],
    };
}

export function V1ListTagsResponseToJSON(json: any): V1ListTagsResponse {
    return V1ListTagsResponseToJSONTyped(json, false);
}

export function V1ListTagsResponseToJSONTyped(value?: V1ListTagsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(Leetcoachv1TagToJSON)),
        'nextPageKey': value['nextPageKey'],
    };
}

