/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1PaginationResponse
 */
export interface V1PaginationResponse {
    /**
     * *
     * The key/pointer string that subsequent List requests should pass to
     * continue the pagination.
     * @type {string}
     * @memberof V1PaginationResponse
     */
    nextPageKey?: string;
    /**
     * 
     * @type {number}
     * @memberof V1PaginationResponse
     */
    nextPageOffset?: number;
    /**
     * *
     * Whether theere are more results.
     * @type {boolean}
     * @memberof V1PaginationResponse
     */
    hasMore?: boolean;
    /**
     * *
     * Total number of results.
     * @type {number}
     * @memberof V1PaginationResponse
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the V1PaginationResponse interface.
 */
export function instanceOfV1PaginationResponse(value: object): value is V1PaginationResponse {
    return true;
}

export function V1PaginationResponseFromJSON(json: any): V1PaginationResponse {
    return V1PaginationResponseFromJSONTyped(json, false);
}

export function V1PaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nextPageKey': json['nextPageKey'] == null ? undefined : json['nextPageKey'],
        'nextPageOffset': json['nextPageOffset'] == null ? undefined : json['nextPageOffset'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
        'totalResults': json['totalResults'] == null ? undefined : json['totalResults'],
    };
}

export function V1PaginationResponseToJSON(json: any): V1PaginationResponse {
    return V1PaginationResponseToJSONTyped(json, false);
}

export function V1PaginationResponseToJSONTyped(value?: V1PaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextPageKey': value['nextPageKey'],
        'nextPageOffset': value['nextPageOffset'],
        'hasMore': value['hasMore'],
        'totalResults': value['totalResults'],
    };
}

