/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Pagination
 */
export interface V1Pagination {
    /**
     * *
     * Instead of an offset an abstract  "page" key is provided that offers
     * an opaque "pointer" into some offset in a result set.
     * @type {string}
     * @memberof V1Pagination
     */
    pageKey?: string;
    /**
     * *
     * If a pagekey is not supported we can also support a direct integer offset
     * for cases where it makes sense.
     * @type {number}
     * @memberof V1Pagination
     */
    pageOffset?: number;
    /**
     * *
     * Number of results to return.
     * @type {number}
     * @memberof V1Pagination
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the V1Pagination interface.
 */
export function instanceOfV1Pagination(value: object): value is V1Pagination {
    return true;
}

export function V1PaginationFromJSON(json: any): V1Pagination {
    return V1PaginationFromJSONTyped(json, false);
}

export function V1PaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Pagination {
    if (json == null) {
        return json;
    }
    return {
        
        'pageKey': json['pageKey'] == null ? undefined : json['pageKey'],
        'pageOffset': json['pageOffset'] == null ? undefined : json['pageOffset'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
    };
}

export function V1PaginationToJSON(json: any): V1Pagination {
    return V1PaginationToJSONTyped(json, false);
}

export function V1PaginationToJSONTyped(value?: V1Pagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageKey': value['pageKey'],
        'pageOffset': value['pageOffset'],
        'pageSize': value['pageSize'],
    };
}

