/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1PlotSectionContent
 */
export interface V1PlotSectionContent {
    /**
     * 
     * @type {string}
     * @memberof V1PlotSectionContent
     */
    data?: string;
}

/**
 * Check if a given object implements the V1PlotSectionContent interface.
 */
export function instanceOfV1PlotSectionContent(value: object): value is V1PlotSectionContent {
    return true;
}

export function V1PlotSectionContentFromJSON(json: any): V1PlotSectionContent {
    return V1PlotSectionContentFromJSONTyped(json, false);
}

export function V1PlotSectionContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PlotSectionContent {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function V1PlotSectionContentToJSON(json: any): V1PlotSectionContent {
    return V1PlotSectionContentToJSONTyped(json, false);
}

export function V1PlotSectionContentToJSONTyped(value?: V1PlotSectionContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

