/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - POSITION_TYPE_BEFORE: Insert before the relative_section_id
 *  - POSITION_TYPE_AFTER: Insert after the relative_section_id
 *  - POSITION_TYPE_END: Append to the end of the design
 * @export
 */
export const V1PositionType = {
    PositionTypeUnspecified: 'POSITION_TYPE_UNSPECIFIED',
    PositionTypeBefore: 'POSITION_TYPE_BEFORE',
    PositionTypeAfter: 'POSITION_TYPE_AFTER',
    PositionTypeEnd: 'POSITION_TYPE_END'
} as const;
export type V1PositionType = typeof V1PositionType[keyof typeof V1PositionType];


export function instanceOfV1PositionType(value: any): boolean {
    for (const key in V1PositionType) {
        if (Object.prototype.hasOwnProperty.call(V1PositionType, key)) {
            if (V1PositionType[key as keyof typeof V1PositionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function V1PositionTypeFromJSON(json: any): V1PositionType {
    return V1PositionTypeFromJSONTyped(json, false);
}

export function V1PositionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PositionType {
    return json as V1PositionType;
}

export function V1PositionTypeToJSON(value?: V1PositionType | null): any {
    return value as any;
}

export function V1PositionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): V1PositionType {
    return value as V1PositionType;
}

