/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ReviewTextContentResponse
 */
export interface V1ReviewTextContentResponse {
    /**
     * 
     * @type {string}
     * @memberof V1ReviewTextContentResponse
     */
    reviewText?: string;
}

/**
 * Check if a given object implements the V1ReviewTextContentResponse interface.
 */
export function instanceOfV1ReviewTextContentResponse(value: object): value is V1ReviewTextContentResponse {
    return true;
}

export function V1ReviewTextContentResponseFromJSON(json: any): V1ReviewTextContentResponse {
    return V1ReviewTextContentResponseFromJSONTyped(json, false);
}

export function V1ReviewTextContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ReviewTextContentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reviewText': json['reviewText'] == null ? undefined : json['reviewText'],
    };
}

export function V1ReviewTextContentResponseToJSON(json: any): V1ReviewTextContentResponse {
    return V1ReviewTextContentResponseToJSONTyped(json, false);
}

export function V1ReviewTextContentResponseToJSONTyped(value?: V1ReviewTextContentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reviewText': value['reviewText'],
    };
}

