/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Content } from './V1Content';
import {
    V1ContentFromJSON,
    V1ContentFromJSONTyped,
    V1ContentToJSON,
    V1ContentToJSONTyped,
} from './V1Content';

/**
 * 
 * @export
 * @interface V1SetContentResponse
 */
export interface V1SetContentResponse {
    /**
     * 
     * @type {V1Content}
     * @memberof V1SetContentResponse
     */
    content?: V1Content;
}

/**
 * Check if a given object implements the V1SetContentResponse interface.
 */
export function instanceOfV1SetContentResponse(value: object): value is V1SetContentResponse {
    return true;
}

export function V1SetContentResponseFromJSON(json: any): V1SetContentResponse {
    return V1SetContentResponseFromJSONTyped(json, false);
}

export function V1SetContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SetContentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : V1ContentFromJSON(json['content']),
    };
}

export function V1SetContentResponseToJSON(json: any): V1SetContentResponse {
    return V1SetContentResponseToJSONTyped(json, false);
}

export function V1SetContentResponseToJSONTyped(value?: V1SetContentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': V1ContentToJSON(value['content']),
    };
}

