/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1SectionType } from './V1SectionType';
import {
    V1SectionTypeFromJSON,
    V1SectionTypeFromJSONTyped,
    V1SectionTypeToJSON,
    V1SectionTypeToJSONTyped,
} from './V1SectionType';

/**
 * 
 * @export
 * @interface V1Section
 */
export interface V1Section {
    /**
     * 
     * @type {Date}
     * @memberof V1Section
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1Section
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1Section
     */
    id?: string;
    /**
     * *
     * Which design this section belong to.
     * @type {string}
     * @memberof V1Section
     */
    designId?: string;
    /**
     * 
     * @type {V1SectionType}
     * @memberof V1Section
     */
    type?: V1SectionType;
    /**
     * *
     * Title of this section.
     * @type {string}
     * @memberof V1Section
     */
    title?: string;
    /**
     * *
     * A description of the section to help make sense of why this is here.
     * @type {string}
     * @memberof V1Section
     */
    description?: string;
    /**
     * *
     * Order of the section in the list of sections.  This is a readonly field.
     * @type {number}
     * @memberof V1Section
     */
    order?: number;
}



/**
 * Check if a given object implements the V1Section interface.
 */
export function instanceOfV1Section(value: object): value is V1Section {
    return true;
}

export function V1SectionFromJSON(json: any): V1Section {
    return V1SectionFromJSONTyped(json, false);
}

export function V1SectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Section {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'designId': json['designId'] == null ? undefined : json['designId'],
        'type': json['type'] == null ? undefined : V1SectionTypeFromJSON(json['type']),
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function V1SectionToJSON(json: any): V1Section {
    return V1SectionToJSONTyped(json, false);
}

export function V1SectionToJSONTyped(value?: V1Section | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'id': value['id'],
        'designId': value['designId'],
        'type': V1SectionTypeToJSON(value['type']),
        'title': value['title'],
        'description': value['description'],
        'order': value['order'],
    };
}

