/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1SectionType = {
    SectionTypeUnspecified: 'SECTION_TYPE_UNSPECIFIED',
    SectionTypeText: 'SECTION_TYPE_TEXT',
    SectionTypeDrawing: 'SECTION_TYPE_DRAWING',
    SectionTypePlot: 'SECTION_TYPE_PLOT'
} as const;
export type V1SectionType = typeof V1SectionType[keyof typeof V1SectionType];


export function instanceOfV1SectionType(value: any): boolean {
    for (const key in V1SectionType) {
        if (Object.prototype.hasOwnProperty.call(V1SectionType, key)) {
            if (V1SectionType[key as keyof typeof V1SectionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function V1SectionTypeFromJSON(json: any): V1SectionType {
    return V1SectionTypeFromJSONTyped(json, false);
}

export function V1SectionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SectionType {
    return json as V1SectionType;
}

export function V1SectionTypeToJSON(value?: V1SectionType | null): any {
    return value as any;
}

export function V1SectionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): V1SectionType {
    return value as V1SectionType;
}

