/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1SuggestedSection
 */
export interface V1SuggestedSection {
    /**
     * 
     * @type {string}
     * @memberof V1SuggestedSection
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SuggestedSection
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SuggestedSection
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SuggestedSection
     */
    getAnswerPrompt?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SuggestedSection
     */
    verifyAnswerPrompt?: string;
}

/**
 * Check if a given object implements the V1SuggestedSection interface.
 */
export function instanceOfV1SuggestedSection(value: object): value is V1SuggestedSection {
    return true;
}

export function V1SuggestedSectionFromJSON(json: any): V1SuggestedSection {
    return V1SuggestedSectionFromJSONTyped(json, false);
}

export function V1SuggestedSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SuggestedSection {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'getAnswerPrompt': json['getAnswerPrompt'] == null ? undefined : json['getAnswerPrompt'],
        'verifyAnswerPrompt': json['verifyAnswerPrompt'] == null ? undefined : json['verifyAnswerPrompt'],
    };
}

export function V1SuggestedSectionToJSON(json: any): V1SuggestedSection {
    return V1SuggestedSectionToJSONTyped(json, false);
}

export function V1SuggestedSectionToJSONTyped(value?: V1SuggestedSection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'type': value['type'],
        'description': value['description'],
        'getAnswerPrompt': value['getAnswerPrompt'],
        'verifyAnswerPrompt': value['verifyAnswerPrompt'],
    };
}

