/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1SuggestedSection } from './V1SuggestedSection';
import {
    V1SuggestedSectionFromJSON,
    V1SuggestedSectionFromJSONTyped,
    V1SuggestedSectionToJSON,
    V1SuggestedSectionToJSONTyped,
} from './V1SuggestedSection';

/**
 * 
 * @export
 * @interface V1SuggestSectionsResponse
 */
export interface V1SuggestSectionsResponse {
    /**
     * 
     * @type {Array<V1SuggestedSection>}
     * @memberof V1SuggestSectionsResponse
     */
    suggestions?: Array<V1SuggestedSection>;
}

/**
 * Check if a given object implements the V1SuggestSectionsResponse interface.
 */
export function instanceOfV1SuggestSectionsResponse(value: object): value is V1SuggestSectionsResponse {
    return true;
}

export function V1SuggestSectionsResponseFromJSON(json: any): V1SuggestSectionsResponse {
    return V1SuggestSectionsResponseFromJSONTyped(json, false);
}

export function V1SuggestSectionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SuggestSectionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestions': json['suggestions'] == null ? undefined : ((json['suggestions'] as Array<any>).map(V1SuggestedSectionFromJSON)),
    };
}

export function V1SuggestSectionsResponseToJSON(json: any): V1SuggestSectionsResponse {
    return V1SuggestSectionsResponseToJSONTyped(json, false);
}

export function V1SuggestSectionsResponseToJSONTyped(value?: V1SuggestSectionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggestions': value['suggestions'] == null ? undefined : ((value['suggestions'] as Array<any>).map(V1SuggestedSectionToJSON)),
    };
}

