/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1TextSectionContent
 */
export interface V1TextSectionContent {
    /**
     * 
     * @type {string}
     * @memberof V1TextSectionContent
     */
    htmlContent?: string;
}

/**
 * Check if a given object implements the V1TextSectionContent interface.
 */
export function instanceOfV1TextSectionContent(value: object): value is V1TextSectionContent {
    return true;
}

export function V1TextSectionContentFromJSON(json: any): V1TextSectionContent {
    return V1TextSectionContentFromJSONTyped(json, false);
}

export function V1TextSectionContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TextSectionContent {
    if (json == null) {
        return json;
    }
    return {
        
        'htmlContent': json['htmlContent'] == null ? undefined : json['htmlContent'],
    };
}

export function V1TextSectionContentToJSON(json: any): V1TextSectionContent {
    return V1TextSectionContentToJSONTyped(json, false);
}

export function V1TextSectionContentToJSONTyped(value?: V1TextSectionContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'htmlContent': value['htmlContent'],
    };
}

