/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Leetcoachv1Tag } from './Leetcoachv1Tag';
import {
    Leetcoachv1TagFromJSON,
    Leetcoachv1TagFromJSONTyped,
    Leetcoachv1TagToJSON,
    Leetcoachv1TagToJSONTyped,
} from './Leetcoachv1Tag';

/**
 * *
 * The request for (partially) updating an Tag.
 * @export
 * @interface V1UpdateTagResponse
 */
export interface V1UpdateTagResponse {
    /**
     * 
     * @type {Leetcoachv1Tag}
     * @memberof V1UpdateTagResponse
     */
    tag?: Leetcoachv1Tag;
}

/**
 * Check if a given object implements the V1UpdateTagResponse interface.
 */
export function instanceOfV1UpdateTagResponse(value: object): value is V1UpdateTagResponse {
    return true;
}

export function V1UpdateTagResponseFromJSON(json: any): V1UpdateTagResponse {
    return V1UpdateTagResponseFromJSONTyped(json, false);
}

export function V1UpdateTagResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateTagResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : Leetcoachv1TagFromJSON(json['tag']),
    };
}

export function V1UpdateTagResponseToJSON(json: any): V1UpdateTagResponse {
    return V1UpdateTagResponseToJSONTyped(json, false);
}

export function V1UpdateTagResponseToJSONTyped(value?: V1UpdateTagResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': Leetcoachv1TagToJSON(value['tag']),
    };
}

