/* tslint:disable */
/* eslint-disable */
/**
 * leetcoach/v1/models.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Design } from './V1Design';
import {
    V1DesignFromJSON,
    V1DesignFromJSONTyped,
    V1DesignToJSON,
    V1DesignToJSONTyped,
} from './V1Design';

/**
 * *
 * The request for (partially) updating an Design.
 * @export
 * @interface V1UpdateDesignResponse
 */
export interface V1UpdateDesignResponse {
    /**
     * 
     * @type {V1Design}
     * @memberof V1UpdateDesignResponse
     */
    design?: V1Design;
}

/**
 * Check if a given object implements the V1UpdateDesignResponse interface.
 */
export function instanceOfV1UpdateDesignResponse(value: object): value is V1UpdateDesignResponse {
    return true;
}

export function V1UpdateDesignResponseFromJSON(json: any): V1UpdateDesignResponse {
    return V1UpdateDesignResponseFromJSONTyped(json, false);
}

export function V1UpdateDesignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateDesignResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'design': json['design'] == null ? undefined : V1DesignFromJSON(json['design']),
    };
}

export function V1UpdateDesignResponseToJSON(json: any): V1UpdateDesignResponse {
    return V1UpdateDesignResponseToJSONTyped(json, false);
}

export function V1UpdateDesignResponseToJSONTyped(value?: V1UpdateDesignResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'design': V1DesignToJSON(value['design']),
    };
}

